"use client";

import { useState } from "react";
import type { JournalTemplate, MoodEntry, TodoItem } from "@/lib/journal-model";

type TemplateProps = { template?: JournalTemplate; title?: string; backgroundVisible?: boolean; checks?: boolean[]; todoItems?: TodoItem[]; moodEntries?: MoodEntry[]; weeklyNotes?: string[]; onTitleChange?: (title: string) => void; onTodoChange?: (id: number, text: string) => void; onTodoToggle?: (id: number) => void; onTodoAdd?: () => void; onTodoDelete?: (id: number) => void; onMoodChange?: (index: number, entry: MoodEntry) => void; onWeeklyChange?: (index: number, note: string) => void; onToggle?: (index: number) => void; onMoveStart?: (event: React.PointerEvent<HTMLElement>) => void; layout?: { x: number; y: number; width: number; height: number }; readOnly?: boolean };

const moodMarkers=[{marker:"😊",color:"#f1c979"},{marker:"😌",color:"#9fc7ad"},{marker:"😐",color:"#aeb9c8"},{marker:"😔",color:"#a99bc3"},{marker:"",color:"#e6a4a1"}];

export function JournalTemplateLayer({ template = "free", title, backgroundVisible = true, checks = [], todoItems = [], moodEntries = [], weeklyNotes = [], onTitleChange, onTodoChange, onTodoToggle, onTodoAdd, onTodoDelete, onMoodChange, onWeeklyChange, onToggle, onMoveStart, layout, readOnly = false }: TemplateProps) {
  const [moodMarker,setMoodMarker]=useState(moodMarkers[0]);
  if (template === "free") return null;
  const count = template === "habit" ? 35 : 7;
  const fallbackTitle = { habit: "Habit tracker", mood: "Mood tracker", weekly: "Weekly plan", todo: "To-do list" }[template];
  const visibleTitle = title || fallbackTitle;
  return <section className={`journal-template template-${template}${backgroundVisible ? "" : " template-transparent"}`} aria-label={visibleTitle} style={layout ? { left: `${layout.x}%`, top: `${layout.y}%`, width: `${layout.width}%`, height: `${layout.height}%` } : undefined}>
    {readOnly ? <h3>{visibleTitle}</h3> : <div className="template-heading"><input aria-label="Template title" value={visibleTitle} maxLength={48} onChange={event => onTitleChange?.(event.target.value)}/><button type="button" className="template-drag-handle" onPointerDown={onMoveStart} aria-label="Move template">drag to move</button></div>}
    {template === "weekly" ? <div className="weekly-columns">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day, index) => <label key={day}><b>{day}</b>{readOnly ? <span>{weeklyNotes[index] || "—"}</span> : <textarea aria-label={`${day} note`} rows={2} maxLength={120} value={weeklyNotes[index] || ""} placeholder="Short note…" onChange={event => onWeeklyChange?.(index,event.target.value)}/>}</label>)}</div>
      : template === "todo" ? <div className="todo-list">{todoItems.map(item => readOnly ? <div className={item.done ? "checked" : ""} key={item.id}><i/>{item.text}</div> : <div className={item.done ? "checked" : ""} key={item.id}><button type="button" aria-label={`${item.done ? "Mark incomplete" : "Complete"} ${item.text || "task"}`} onClick={() => onTodoToggle?.(item.id)}><i/></button><input aria-label="Task text" value={item.text} placeholder="Write a task…" onChange={event => onTodoChange?.(item.id, event.target.value)}/><button type="button" className="todo-delete" aria-label={`Delete ${item.text || "task"}`} onClick={() => onTodoDelete?.(item.id)}>×</button></div>)}{readOnly ? null : <button type="button" className="todo-add" aria-label="Add task" onClick={onTodoAdd}>＋ Add task</button>}</div>
      : template === "mood" ? <div className="mood-tracker">{readOnly ? null : <div className="mood-palette" aria-label="Mood marker palette">{moodMarkers.map((entry,index)=><button type="button" key={`${entry.marker}-${entry.color}`} className={moodMarker===entry?"active":""} style={{backgroundColor:entry.color}} onClick={()=>setMoodMarker(entry)} aria-label={entry.marker?`Use ${entry.marker}`:`Use colour ${index+1}`}>{entry.marker}</button>)}</div>}<div className="mood-days">{Array.from({length:31},(_,index)=>{const entry=moodEntries[index];return <button type="button" key={index} disabled={readOnly} onClick={()=>onMoodChange?.(index,moodMarker)} style={{backgroundColor:entry?.color||"transparent"}} aria-label={`${visibleTitle} day ${index+1}`}><small>{index+1}</small><span>{entry?.marker}</span></button>})}</div></div>
      : <div className="tracker-grid">{Array.from({ length: count }, (_, index) => <button type="button" key={index} className={checks[index] ? "checked" : ""} disabled={readOnly} onClick={() => onToggle?.(index)} aria-label={`${visibleTitle} item ${index + 1}`}>{index + 1}</button>)}</div>}
  </section>;
}
