"use client";
/* eslint-disable @next/next/no-img-element -- Journal images are local data URLs; Next Image cannot optimize them. */
import { useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { JournalLibrary } from "@/components/journal-library";
import type { Book, Joy, PageData, Photo, Sticker } from "@/lib/journal-model";
import { PageFinder } from "@/components/page-finder";
import { compressImage, readFileAsDataUrl } from "@/lib/image-compression";
import { createEncryptedJournal, deleteEncryptedJournal, listEncryptedJournals, updateEncryptedJournal } from "@/lib/journal-repository";
import { getAccountMasterKey, hasAccountMasterKey } from "@/lib/key-vault";
import { markCloudDraftSynced, readCloudDraft, writeCloudDraft } from "@/lib/cloud-drafts";
import { makeBackup, parseBackup } from "@/lib/local-backup";
import { downloadMigrationBackup, getLocalMigrationSources, migrateLocalJournals, removeMigratedLocalCopies, type MigrationSource } from "@/lib/local-migration";
import { loadEncryptedPages, syncEncryptedPages } from "@/lib/page-repository";
import { moveItem, removeItem } from "@/lib/page-order";
import { isOfflineSyncError, OFFLINE_DRAFT_MESSAGE } from "@/lib/sync-errors";
import { exportJournalPage } from "@/lib/page-export";
import { downloadBackupFile, importCloudBackup, makeCloudBackup } from "@/lib/cloud-backup";
import { ArrowLeft,ArrowRight,BookOpen,Brush,ChevronLeft,ChevronRight,FileText,Focus,Frame,ImagePlus,Images,Layers,Palette,Plus,Redo2,RotateCcw,Share2,Sparkles,Trash2,Type,Undo2,X } from "lucide-react";

const stickers=["🌼","🍓","🎀","☁️","🪩","🦋","⭐","🍵","📚","🌙","💌","🧸"];
const themes=[{name:"Blush",color:"#df9b9b",pale:"#f8e9e5"},{name:"Sage",color:"#76947a",pale:"#e7eee3"},{name:"Sky",color:"#7897b5",pale:"#e5eef5"},{name:"Butter",color:"#c39b43",pale:"#f7efd6"},{name:"Lilac",color:"#907ba6",pale:"#eee8f3"}];
type Drag={kind:"sticker"|"photo";id:number;dx:number;dy:number};
const DEFAULT_BOOKS:Book[]=[{id:"august",title:"My August Journal",tone:"rose",label:"summer notes"},{id:"wedding",title:"Wedding Memories",tone:"sage",label:"our story"},{id:"little",title:"Little Things",tone:"blue",label:"everyday magic"}];
const BOOKS_STORAGE_KEY="pin-paper-journal-books";
const storageKey=(bookId:string)=>bookId==="august"?"pin-paper-journal":`pin-paper-journal-${bookId}`;

export default function Home({ cloudUserId }: { cloudUserId?: string }){
 const router=useRouter();
 const isCloud=Boolean(cloudUserId);
 const[screen,setScreen]=useState<"shelf"|"editor">("shelf"),[activeBook,setActiveBook]=useState("august"),[tool,setTool]=useState("write"),[focus,setFocus]=useState(false);
 const[turning,setTurning]=useState<""|"next"|"prev">("");
 const[singlePage,setSinglePage]=useState(false);
 const[books,setBooks]=useState<Book[]>(isCloud?[]:DEFAULT_BOOKS),[libraryBusy,setLibraryBusy]=useState(isCloud),[libraryMessage,setLibraryMessage]=useState(""),[migrationSources,setMigrationSources]=useState<MigrationSource[]>([]),[migrationBusy,setMigrationBusy]=useState(false),[migratedLocalIds,setMigratedLocalIds]=useState<string[]>([]);
 const[note,setNote]=useState(""),[title,setTitle]=useState("Today, I want to remember…"),[theme,setTheme]=useState(themes[0]);
 const[placed,setPlaced]=useState<Sticker[]>([{id:1,value:"🌼",x:84,y:12,rotation:8},{id:2,value:"🎀",x:8,y:72,rotation:-8}]);
 const[photos,setPhotos]=useState<Photo[]>([]),[selected,setSelected]=useState<number|null>(null),[saveState,setSaveState]=useState<"idle"|"saving"|"saved"|"offline"|"error">("idle"),[saveError,setSaveError]=useState(""),[assetProgress,setAssetProgress]=useState<{completed:number;total:number}|null>(null);
 const[drawing,setDrawing]=useState(false),[penColor,setPenColor]=useState("#9c6868"),[drawingData,setDrawingData]=useState(""),[drawingAssetId,setDrawingAssetId]=useState<string|undefined>();
 const[joys,setJoys]=useState<Joy[]>([{id:1,text:"slow mornings",done:false},{id:2,text:"good music",done:false},{id:3,text:"something sweet",done:false}]);
 const[joysVisible,setJoysVisible]=useState(true);
 const[pattern,setPattern]=useState("lined"),[paperColor,setPaperColor]=useState("#fffdf7"),[font,setFont]=useState("hand"),[fontSize,setFontSize]=useState(18),[textColor,setTextColor]=useState("#66564b");
 const[pages,setPages]=useState<PageData[]>([]),[pageIndex,setPageIndex]=useState(0);
 const[pageName,setPageName]=useState("Today"),[pageDate,setPageDate]=useState(new Date().toISOString().slice(0,10)),[pageSearch,setPageSearch]=useState("");
 const[canUndo,setCanUndo]=useState(false),[canRedo,setCanRedo]=useState(false);
 const pageRef=useRef<HTMLDivElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),drag=useRef<Drag|null>(null),painting=useRef(false),hydratedBook=useRef("");
 const history=useRef<{pageId:string|number|null;past:string[];present:string;future:string[]}>({pageId:null,past:[],present:"",future:[]});
 const syncQueue=useRef<Promise<void>>(Promise.resolve()),syncRequest=useRef(0);
 useEffect(()=>{const q=window.matchMedia("(max-width: 650px)"),sync=()=>setSinglePage(q.matches);sync();q.addEventListener("change",sync);return()=>q.removeEventListener("change",sync)},[]);
 useEffect(()=>{if(isCloud)return;let cancelled=false;try{const raw=localStorage.getItem(BOOKS_STORAGE_KEY);if(raw){const parsed=JSON.parse(raw);if(Array.isArray(parsed)&&parsed.length)queueMicrotask(()=>{if(!cancelled)setBooks(parsed)})}}catch{/* Keep the built-in shelf if old data is malformed. */}return()=>{cancelled=true}},[isCloud]);
 useEffect(()=>{if(!isCloud)return;if(!hasAccountMasterKey()){router.replace("/");return}let cancelled=false;const load=async()=>{setLibraryBusy(true);try{const loaded=await listEncryptedJournals(getAccountMasterKey());if(!cancelled){setBooks(loaded);setMigrationSources(getLocalMigrationSources());setLibraryMessage(loaded.length?"Your encrypted journals are synced.":"Create your first encrypted journal.")}}catch(error){if(!cancelled)setLibraryMessage(error instanceof Error?error.message:"Your encrypted journals could not be loaded.")}finally{if(!cancelled)setLibraryBusy(false)}};void load();return()=>{cancelled=true}},[isCloud,router]);
 const resetBook=()=>{setPages([]);setPageIndex(0);setPageName("Today");setPageDate(new Date().toISOString().slice(0,10));setNote("");setTitle("Today, I want to remember…");setPlaced([]);setPhotos([]);setDrawingData("");setDrawingAssetId(undefined);setJoys([{id:1,text:"slow mornings",done:false},{id:2,text:"good music",done:false},{id:3,text:"something sweet",done:false}]);setJoysVisible(true);setPattern("lined");setPaperColor("#fffdf7");setFont("hand");setFontSize(18);setTextColor("#66564b");setTheme(themes[0]);setSelected(null)};
 const hydrate=(raw:string|null)=>{if(!raw){resetBook();return}try{const d=JSON.parse(raw);const first=d.pages?.[0]||d;if(!first){resetBook();return}setPages(d.pages||[]);setPageIndex(0);setPageName(first.pageName||"Today");setPageDate(first.pageDate||new Date().toISOString().slice(0,10));setNote(first.note||"");setTitle(first.title||"Today, I want to remember…");setPlaced(first.placed||[]);setPhotos(first.photos||(first.photo?[{id:1,src:first.photo,x:60,y:30,rotation:2,framed:true,z:1,size:180,shape:"square"}]:[]));setDrawingData(first.drawingData||"");setDrawingAssetId(first.drawingAssetId);setJoys(first.joys||[]);setJoysVisible(first.joysVisible!==false);setPattern(first.pattern||"lined");setPaperColor(first.paperColor||"#fffdf7");setFont(first.font||"hand");setFontSize(first.fontSize||18);setTextColor(first.textColor||"#66564b");setTheme(themes.find(t=>t.name===d.theme)||themes[0]);setSelected(null)}catch{resetBook()}};
 const openBook=async(id:string)=>{history.current={pageId:null,past:[],present:"",future:[]};setCanUndo(false);setCanRedo(false);setActiveBook(id);setSaveState(isCloud?"saving":"idle");setSaveError("");setScreen("editor");if(!isCloud){hydrate(localStorage.getItem(storageKey(id)));hydratedBook.current=id;return}const draft=readCloudDraft(id);if(draft?.pendingSync){hydrate(JSON.stringify(draft));hydratedBook.current=id;setSaveError("Offline changes are safe on this device and waiting to sync.");void queueCloudSync(id,draft.pages,draft.theme,true);return}try{const loaded=await loadEncryptedPages(getAccountMasterKey(),id);if(loaded.pages.length)hydrate(JSON.stringify({pages:loaded.pages,theme:"Blush"}));else resetBook();hydratedBook.current=id;setSaveState("saved")}catch(error){if(draft){hydrate(JSON.stringify(draft));hydratedBook.current=id}setSaveState("error");setSaveError(error instanceof Error?error.message:"Encrypted pages could not be loaded.")}};
 useEffect(()=>{const c=canvasRef.current,p=pageRef.current;if(!c||!p)return;const resize=()=>{c.width=p.clientWidth*devicePixelRatio;c.height=p.clientHeight*devicePixelRatio;c.style.width=p.clientWidth+"px";c.style.height=p.clientHeight+"px";const ctx=c.getContext("2d");ctx?.scale(devicePixelRatio,devicePixelRatio);if(drawingData){const im=new Image();im.onload=()=>ctx?.drawImage(im,0,0,p.clientWidth,p.clientHeight);im.src=drawingData}};resize();window.addEventListener("resize",resize);return()=>window.removeEventListener("resize",resize)},[drawingData]);
 const snapshot=():PageData=>({id:pages[pageIndex]?.id||(isCloud?crypto.randomUUID():Date.now()),pageName,pageDate,title,note,placed,photos,drawingData,drawingAssetId,joys,joysVisible,pattern,paperColor,font,fontSize,textColor});
 const queueCloudSync=(journalId:string,next:PageData[],themeName:string,quiet=false)=>{if(!cloudUserId)return Promise.resolve();const request=++syncRequest.current;if(!quiet)setSaveState("saving");syncQueue.current=syncQueue.current.catch(()=>undefined).then(async()=>{if(!navigator.onLine)throw new TypeError("Offline");const synced=await syncEncryptedPages({userId:cloudUserId,journalId,masterKey:getAccountMasterKey(),pages:next,onAssetProgress:(completed,total)=>{if(request===syncRequest.current)setAssetProgress({completed,total})}});if(request===syncRequest.current){markCloudDraftSynced(journalId,synced,themeName);setAssetProgress(null);setSaveState("saved");setSaveError("")}}).catch(error=>{if(request===syncRequest.current){setAssetProgress(null);if(isOfflineSyncError(error)){setSaveState("offline");setSaveError(OFFLINE_DRAFT_MESSAGE)}else{setSaveState("error");setSaveError(error instanceof Error?error.message:"Cloud sync failed. Your local draft is safe.")}}});return syncQueue.current};
 const persistPages=(next:PageData[],manual=false)=>{try{if(isCloud){writeCloudDraft(activeBook,next,theme.name,true);void queueCloudSync(activeBook,next,theme.name,!manual)}else{localStorage.setItem(storageKey(activeBook),JSON.stringify({version:1,pages:next,theme:theme.name,updatedAt:new Date().toISOString()}));if(manual)setSaveState("saved")}return true}catch(error){setSaveState("error");setSaveError(error instanceof DOMException&&error.name==="QuotaExceededError"?"Browser storage is full. Remove some photos or export this page before leaving.":"This journal could not be saved. Please keep this tab open and try again.");return false}};
 const save=()=>{setSaveState("saving");const next=pages.length?pages.map((p,i)=>i===pageIndex?snapshot():p):[snapshot()];setPages(next);setDrawingData(next[pageIndex].drawingData);return persistPages(next,true)};
 // These effects intentionally capture the latest render's persistence functions and are recreated with all editor state below.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(screen!=="editor"||hydratedBook.current!==activeBook)return;const persist=()=>{const current:PageData={id:pages[pageIndex]?.id||(isCloud?crypto.randomUUID():Date.now()),pageName,pageDate,title,note,placed,photos,drawingData,drawingAssetId,joys,joysVisible,pattern,paperColor,font,fontSize,textColor};const next=pages.length?pages.map((p,i)=>i===pageIndex?current:p):[current];persistPages(next)};const timer=window.setTimeout(persist,900);window.addEventListener("pagehide",persist);return()=>{window.clearTimeout(timer);window.removeEventListener("pagehide",persist)}},[screen,activeBook,pages,pageIndex,pageName,pageDate,title,note,placed,photos,drawingData,drawingAssetId,joys,joysVisible,pattern,paperColor,font,fontSize,textColor,theme,isCloud]);
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!isCloud)return;const retry=()=>{const draft=readCloudDraft(activeBook);if(screen==="editor"&&draft?.pendingSync)void queueCloudSync(activeBook,draft.pages,draft.theme,true)};window.addEventListener("online",retry);return()=>window.removeEventListener("online",retry)},[isCloud,activeBook,screen]);
 const loadPage=(p:PageData,i:number)=>{setPageIndex(i);setPageName(p.pageName||`Page ${i+1}`);setPageDate(p.pageDate||"");setTitle(p.title);setNote(p.note);setPlaced(p.placed);setPhotos(p.photos);setDrawingData(p.drawingData);setDrawingAssetId(p.drawingAssetId);setJoys(p.joys||[]);setJoysVisible(p.joysVisible!==false);setPattern(p.pattern);setPaperColor(p.paperColor);setFont(p.font);setFontSize(p.fontSize);setTextColor(p.textColor);setSelected(null)};
 const goPage=(i:number)=>{if(turning||i===pageIndex||i<0||i>=Math.max(1,pages.length))return;const next=pages.length?pages.map((p,n)=>n===pageIndex?snapshot():p):[snapshot()];setPages(next);setTurning(i>pageIndex?"next":"prev");window.setTimeout(()=>{loadPage(next[i],i);setTurning("")},360)};
 const selectPage=(i:number)=>{if(i===pageIndex||!pages[i])return;const next=pages.map((p,n)=>n===pageIndex?snapshot():p);setPages(next);loadPage(next[i],i)};
 const addPage=()=>{const current=pages.length?pages.map((p,i)=>i===pageIndex?snapshot():p):[snapshot()];const blank:PageData={id:isCloud?crypto.randomUUID():Date.now(),pageName:`Page ${current.length+1}`,pageDate:new Date().toISOString().slice(0,10),title:"A fresh page…",note:"",placed:[],photos:[],drawingData:"",joys:[],joysVisible:true,pattern,paperColor,font,fontSize,textColor};const next=[...current,blank];setPages(next);loadPage(blank,next.length-1)};
 const deletePage=()=>{if(!window.confirm(`Delete “${pageName||`Page ${pageIndex+1}`}”? This cannot be undone.`))return;const current=pages.length?pages.map((p,i)=>i===pageIndex?snapshot():p):[snapshot()];if(current.length===1){resetBook();history.current={pageId:null,past:[],present:"",future:[]};return}const next=removeItem(current,pageIndex),nextIndex=Math.min(pageIndex,next.length-1);setPages(next);loadPage(next[nextIndex],nextIndex)};
 const movePage=(direction:-1|1)=>{const target=pageIndex+direction;if(target<0||target>=Math.max(1,pages.length))return;const current=pages.length?pages.map((p,i)=>i===pageIndex?snapshot():p):[snapshot()],next=moveItem(current,pageIndex,target);setPages(next);loadPage(next[target],target)};
 const sharePage=async()=>{try{await exportJournalPage(snapshot(),title);setSaveError("")}catch(error){setSaveError(error instanceof Error?`Page export failed: ${error.message}`:"The page could not be exported.")}};
 const addSticker=(value:string)=>setPlaced(p=>[...p,{id:Date.now(),value,x:18+Math.random()*58,y:16+Math.random()*60,rotation:-10+Math.random()*20}]);
 const upload=async(files:FileList|null)=>{for(const [i,file] of Array.from(files||[]).entries()){try{const compressed=await compressImage(file),src=await readFileAsDataUrl(compressed),id=Date.now()+i;setPhotos(p=>[...p,{id,src,x:20+i*5,y:22+i*5,rotation:-4+i*3,framed:true,z:Math.max(0,...p.map(x=>x.z))+1,size:180,shape:"square"}]);setSelected(id);setSaveError("")}catch(error){setSaveError(error instanceof Error?error.message:`${file.name} could not be added.`)}}};
 const move=(e:React.PointerEvent)=>{if(!drag.current||!pageRef.current||drawing)return;const b=pageRef.current.getBoundingClientRect(),x=Math.max(0,Math.min(88,((e.clientX-b.left-drag.current.dx)/b.width)*100)),y=Math.max(0,Math.min(84,((e.clientY-b.top-drag.current.dy)/b.height)*100));if(drag.current.kind==="sticker")setPlaced(a=>a.map(s=>s.id===drag.current?.id?{...s,x,y}:s));else setPhotos(a=>a.map(s=>s.id===drag.current?.id?{...s,x,y}:s))};
 const beginDrag=(e:React.PointerEvent,kind:Drag["kind"],id:number)=>{if(drawing)return;const b=e.currentTarget.getBoundingClientRect();drag.current={kind,id,dx:e.clientX-b.left,dy:e.clientY-b.top};e.currentTarget.setPointerCapture(e.pointerId)};
 const draw=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!painting.current)return;const c=e.currentTarget,b=c.getBoundingClientRect(),ctx=c.getContext("2d");if(!ctx)return;ctx.lineTo(e.clientX-b.left,e.clientY-b.top);ctx.strokeStyle=penColor;ctx.lineWidth=3;ctx.lineCap="round";ctx.lineJoin="round";ctx.stroke()};
 const startDraw=(e:React.PointerEvent<HTMLCanvasElement>)=>{painting.current=true;const b=e.currentTarget.getBoundingClientRect(),ctx=e.currentTarget.getContext("2d");ctx?.beginPath();ctx?.moveTo(e.clientX-b.left,e.clientY-b.top);e.currentTarget.setPointerCapture(e.pointerId)};
 const clearDrawing=()=>{const c=canvasRef.current;c?.getContext("2d")?.clearRect(0,0,c.width,c.height);setDrawingData("");setDrawingAssetId(undefined)};
 const finishDrawing=()=>{painting.current=false;setDrawingData(canvasRef.current?.toDataURL()||"");setDrawingAssetId(undefined)};
 const editPhoto=(fn:(p:Photo)=>Photo)=>setPhotos(a=>a.map(p=>p.id===selected?fn(p):p));
 const active=photos.find(p=>p.id===selected);
 const spreadStart=Math.floor(pageIndex/2)*2,companionIndex=pageIndex===spreadStart?spreadStart+1:spreadStart,companion=pages[companionIndex];
 const previousTarget=singlePage?pageIndex-1:spreadStart-2;
 const nextTarget=singlePage?pageIndex+1:spreadStart+2;
 const currentPreview:PageData={id:pages[pageIndex]?.id||0,pageName,pageDate,title,note,placed,photos,drawingData,drawingAssetId,joys,joysVisible,pattern,paperColor,font,fontSize,textColor};
 const currentSerialized=JSON.stringify(currentPreview);
 useEffect(()=>{if(screen!=="editor")return;const pageId=currentPreview.id;if(history.current.pageId!==pageId){history.current={pageId,past:[],present:currentSerialized,future:[]};queueMicrotask(()=>{setCanUndo(false);setCanRedo(false)});return}const timer=window.setTimeout(()=>{if(history.current.present&&history.current.present!==currentSerialized){history.current.past=[...history.current.past.slice(-49),history.current.present];history.current.present=currentSerialized;history.current.future=[];setCanUndo(true);setCanRedo(false)}},450);return()=>window.clearTimeout(timer)},[screen,currentPreview.id,currentSerialized]);
 const restoreHistory=(serialized:string)=>{const restored=JSON.parse(serialized) as PageData;setPages(existing=>existing.length?existing.map((page,index)=>index===pageIndex?restored:page):[restored]);loadPage(restored,pageIndex)};
 const undo=()=>{const state=history.current,previous=state.past.at(-1);if(!previous)return;state.future=[state.present,...state.future];state.past=state.past.slice(0,-1);state.present=previous;restoreHistory(previous);setCanUndo(state.past.length>0);setCanRedo(true)};
 const redo=()=>{const state=history.current,next=state.future[0];if(!next)return;state.past=[...state.past,state.present];state.future=state.future.slice(1);state.present=next;restoreHistory(next);setCanUndo(true);setCanRedo(state.future.length>0)};
 const storeBooks=(next:Book[])=>{localStorage.setItem(BOOKS_STORAGE_KEY,JSON.stringify(next));setBooks(next)};
 const createBook=async()=>{if(isCloud&&cloudUserId){setLibraryBusy(true);try{const book=await createEncryptedJournal(cloudUserId,getAccountMasterKey(),{title:"Untitled Journal",tone:"kraft",label:"new memories"});setBooks(current=>[...current,book]);setLibraryMessage("Encrypted journal created.");openBook(book.id)}catch(error){setLibraryMessage(error instanceof Error?error.message:"The encrypted journal could not be created.")}finally{setLibraryBusy(false)}return}const id="book-"+Date.now(),next=[...books,{id,title:"Untitled Journal",tone:"kraft",label:"new memories"}];try{storeBooks(next);openBook(id)}catch{setSaveError("The new journal could not be saved because browser storage is unavailable.")}};
 const updateBookMetadata=async(id:string,changes:Partial<Omit<Book,"id">>,successMessage:string)=>{const book=books.find(item=>item.id===id);if(isCloud&&book){setLibraryBusy(true);try{await updateEncryptedJournal(getAccountMasterKey(),book,changes);setBooks(current=>current.map(item=>item.id===id?{...item,...changes}:item));setLibraryMessage(successMessage)}catch(error){setLibraryMessage(error instanceof Error?error.message:"The encrypted journal could not be updated.")}finally{setLibraryBusy(false)}return}try{storeBooks(books.map(item=>item.id===id?{...item,...changes}:item))}catch{setSaveError("The journal could not be updated.")}};
 const renameBook=(id:string,newTitle:string)=>updateBookMetadata(id,{title:newTitle},"Encrypted journal renamed.");
 const changeBookTone=(id:string,tone:string)=>updateBookMetadata(id,{tone},"A new cover colour was saved.");
 const migrateLocal=async()=>{if(!cloudUserId||!migrationSources.length)return;setMigrationBusy(true);try{const sourceIds=migrationSources.map(source=>source.book.id);downloadMigrationBackup(migrationSources);const migrated=await migrateLocalJournals({userId:cloudUserId,masterKey:getAccountMasterKey(),sources:migrationSources});setBooks(current=>[...current,...migrated.filter(book=>!current.some(existing=>existing.id===book.id))]);setMigratedLocalIds(sourceIds);setMigrationSources(getLocalMigrationSources());setLibraryMessage(`${migrated.length} local ${migrated.length===1?"journal":"journals"} encrypted and moved. Local copies were kept.`)}catch(error){setLibraryMessage(error instanceof Error?error.message:"Local journals could not be migrated. Their local copies are safe.")}finally{setMigrationBusy(false)}};
 const removeMigratedLocal=()=>{if(!migratedLocalIds.length||!window.confirm("Remove the migrated local copies from this device? Your encrypted cloud journals and downloaded backup will remain."))return;const removed=removeMigratedLocalCopies(migratedLocalIds);setMigratedLocalIds([]);setLibraryMessage(`${removed} migrated local ${removed===1?"copy":"copies"} removed from this device.`)};
 const deleteBook=async(book:Book)=>{if(!window.confirm(`Delete “${book.title}” and all of its ${isCloud?"encrypted cloud":"locally saved"} pages? This cannot be undone.`))return;if(isCloud){setLibraryBusy(true);try{await deleteEncryptedJournal(book.id);localStorage.removeItem(storageKey(book.id));setBooks(current=>current.filter(item=>item.id!==book.id));setLibraryMessage("Encrypted journal deleted.")}catch(error){setLibraryMessage(error instanceof Error?error.message:"The encrypted journal could not be deleted.")}finally{setLibraryBusy(false)}return}try{localStorage.removeItem(storageKey(book.id));storeBooks(books.filter(item=>item.id!==book.id))}catch{setSaveError("The journal could not be deleted.")}};
 const exportBackup=async()=>{if(isCloud){setLibraryBusy(true);setLibraryMessage("Preparing your decrypted, portable backup on this device…");try{downloadBackupFile(await makeCloudBackup(books,getAccountMasterKey()));setLibraryMessage("Backup downloaded. Keep it somewhere private.")}catch(error){setLibraryMessage(error instanceof Error?error.message:"The encrypted cloud backup could not be created.")}finally{setLibraryBusy(false)}return}try{downloadBackupFile(makeBackup(books,id=>localStorage.getItem(storageKey(id))))}catch{setSaveError("The local backup could not be created.")}};
 const importBackup=async(file:File)=>{try{const backup=parseBackup(await file.text());if(isCloud&&cloudUserId){if(!window.confirm(`Import ${backup.books.length} journals as new encrypted cloud journals? Existing journals will not be replaced.`))return;setLibraryBusy(true);setLibraryMessage("Encrypting and importing your backup…");try{const imported=await importCloudBackup({backup,userId:cloudUserId,masterKey:getAccountMasterKey()});setBooks(current=>[...current,...imported]);setLibraryMessage(`${imported.length} ${imported.length===1?"journal":"journals"} imported as encrypted cloud copies.`)}finally{setLibraryBusy(false)}return}if(!window.confirm(`Import ${backup.books.length} journals? This replaces the journals currently stored in this browser.`))return;for(const book of books)localStorage.removeItem(storageKey(book.id));for(const book of backup.books){const data=backup.journals[book.id];if(data)localStorage.setItem(storageKey(book.id),JSON.stringify(data))}storeBooks(backup.books);setSaveError("")}catch(error){if(isCloud)setLibraryMessage(error instanceof Error?error.message:"The cloud backup could not be imported.");else setSaveError(error instanceof Error?error.message:"The backup could not be imported.")}};
 if(screen==="shelf")return <JournalLibrary books={books} busy={libraryBusy} message={libraryMessage} localMigrationCount={migrationSources.length} migrationBusy={migrationBusy} migratedLocalCount={migratedLocalIds.length} onMigrateLocal={migrateLocal} onRemoveMigratedLocal={removeMigratedLocal} onCreate={createBook} onDelete={deleteBook} onExport={exportBackup} onImport={importBackup} onOpen={openBook} onRename={renameBook} onToneChange={changeBookTone}/>;
 return <main className={"desk-screen "+(focus?"focus-mode":"")} style={{"--ink":theme.color,"--wash":theme.pale} as React.CSSProperties}>
 <header className="topbar"><button className="back-library" onClick={()=>{if(save())setScreen("shelf")}}><BookOpen/> My journals</button><div className="page-history"><Button variant="ghost" size="icon" disabled={!canUndo} onClick={undo} title="Undo"><Undo2/></Button><Button variant="ghost" size="icon" disabled={!canRedo} onClick={redo} title="Redo"><Redo2/></Button><Button variant="ghost" size="icon" disabled={pageIndex===0} onClick={()=>movePage(-1)} title="Move page left"><ArrowLeft/></Button><Button variant="ghost" size="icon" disabled={pageIndex>=pages.length-1} onClick={()=>movePage(1)} title="Move page right"><ArrowRight/></Button><Button variant="ghost" size="icon" onClick={deletePage} title="Delete page"><Trash2/></Button></div><div className="page-nav"><Button variant="ghost" size="icon" disabled={previousTarget<0} onClick={()=>goPage(previousTarget)}><ChevronLeft/></Button><span>{singlePage?(pageName||`Page ${pageIndex+1}`):`Pages ${spreadStart+1}–${Math.min(spreadStart+2,Math.max(1,pages.length))}`}</span><Button variant="ghost" size="icon" disabled={nextTarget>=Math.max(1,pages.length)} onClick={()=>goPage(nextTarget)}><ChevronRight/></Button><Button variant="outline" size="sm" onClick={addPage}><Plus/> New page</Button></div><Button variant="ghost" size="icon" onClick={()=>setFocus(v=>!v)} title="Focus mode"><Focus/></Button><Button variant="outline" onClick={sharePage}><Share2/> Export page</Button><Button onClick={save} className="save-button" aria-live="polite">{saveState==="saving"?"Saving…":saveState==="saved"?"Saved quietly ♡":saveState==="offline"?"Saved on this device ♡":saveState==="error"?"Try saving again":"Save"}</Button></header>
  {saveError&&<div className="save-error" role="alert">{saveError}<button onClick={()=>setSaveError("")} aria-label="Dismiss">×</button></div>}
  <PageFinder activeIndex={pageIndex} onAdd={addPage} onSelect={goPage} pages={pages.length?pages:[currentPreview]} query={pageSearch} setQuery={setPageSearch}/>
  <div className="workspace"><nav className="page-tabs">{["Today","Dreams","Us","Ideas"].map((x,i)=><button key={x} className={i===pageIndex?"active":""} onClick={()=>i<pages.length&&goPage(i)}>{x}</button>)}<button onClick={addPage}>＋</button></nav><aside className="toolbox" data-tool={tool}><div className="tool-rail">{[{id:"write",icon:<Type/>,n:"Write"},{id:"photos",icon:<Images/>,n:"Photos"},{id:"stickers",icon:<Sparkles/>,n:"Stickers"},{id:"draw",icon:<Brush/>,n:"Draw"},{id:"paper",icon:<FileText/>,n:"Paper"}].map(t=><button key={t.id} className={tool===t.id?"active":""} onClick={()=>setTool(t.id)}>{t.icon}<span>{t.n}</span></button>)}</div><div className="tool-drawer"><button className="drawer-close" onClick={()=>setTool("")}><X/></button><div className="tape">creative drawer</div>
   <section className="tool-stickers"><h2><Sparkles size={16}/> Stickers & details</h2><p>Tap to drop one onto the page.</p><div className="sticker-grid">{stickers.map(s=><button key={s} onClick={()=>addSticker(s)}>{s}</button>)}</div></section>
   <section className="tool-paper"><h2><Palette size={16}/> Colour mood</h2><div className="swatches">{themes.map(t=><button key={t.name} onClick={()=>setTheme(t)} className={theme.name===t.name?"active":""} style={{background:t.color}} aria-label={t.name}/>)}</div><h2 className="subhead">Paper surface</h2><div className="compact-controls"><select value={pattern} onChange={e=>setPattern(e.target.value)}><option value="lined">Lined</option><option value="dots">Dotted</option><option value="grid">Grid</option><option value="plain">Plain</option></select><label>Paper <input type="color" value={paperColor} onChange={e=>setPaperColor(e.target.value)}/></label></div></section>
   <section className="tool-write"><h2>𝑨 Writing style</h2><div className="compact-controls"><select value={font} onChange={e=>setFont(e.target.value)}><option value="hand">Handwritten</option><option value="serif">Classic serif</option><option value="sans">Clean sans</option><option value="mono">Typewriter</option></select><label>Size <input type="range" min="12" max="34" value={fontSize} onChange={e=>setFontSize(+e.target.value)}/><b>{fontSize}</b></label><label>Ink <input type="color" value={textColor} onChange={e=>setTextColor(e.target.value)}/></label>{!joysVisible&&<Button variant="outline" size="sm" onClick={()=>setJoysVisible(true)}>＋ Add Little Joys card</Button>}</div></section>
   <section className="tool-photos"><h2><ImagePlus size={16}/> Photos</h2><p>{assetProgress?`Encrypting & uploading ${assetProgress.completed}/${assetProgress.total}…`:"Add several, then arrange them freely."}</p><label className="upload"><input multiple type="file" accept="image/*" onChange={e=>upload(e.target.files)}/><ImagePlus size={18}/> Add pictures</label>
    {active&&<div className="photo-tools"><label className="size-control">Size <input type="range" min="80" max="420" value={active.size||180} onChange={e=>editPhoto(p=>({...p,size:+e.target.value}))}/></label><label className="size-control">Rotate <input type="range" min="-180" max="180" value={active.rotation} onChange={e=>editPhoto(p=>({...p,rotation:+e.target.value}))}/><b>{active.rotation}°</b></label><label className="shape-control">Shape <select value={active.shape||"square"} onChange={e=>editPhoto(p=>({...p,shape:e.target.value as Photo["shape"]}))}><option value="square">Square</option><option value="round">Circle</option><option value="soft">Soft corners</option><option value="wavy">Wavy</option></select></label><Button variant="outline" size="sm" onClick={()=>editPhoto(p=>({...p,framed:!p.framed}))}><Frame/> {active.framed?"Remove frame":"Add frame"}</Button><Button variant="outline" size="sm" onClick={()=>editPhoto(p=>({...p,z:Math.max(...photos.map(x=>x.z))+1}))}><Layers/> Bring front</Button><Button variant="outline" size="sm" onClick={()=>setPhotos(a=>a.filter(p=>p.id!==selected))}><Trash2/> Delete</Button></div>}
   </section>
   <section className="tool-draw"><h2><Brush size={16}/> Free drawing</h2><div className="draw-tools"><input type="color" value={penColor} onChange={e=>setPenColor(e.target.value)} aria-label="Pen colour"/><Button size="sm" variant={drawing?"default":"outline"} onClick={()=>setDrawing(v=>!v)}>{drawing?"Drawing on":"Start drawing"}</Button><Button size="sm" variant="ghost" onClick={clearDrawing}>Erase all</Button></div></section>
   <Button variant="ghost" className="clear-button" onClick={()=>{setPlaced([]);setPhotos([]);clearDrawing()}}><RotateCcw size={15}/> Clear decorations</Button>
  </div></aside>
  <section className="journal-shell">
   <div className={"book-spread "+(turning?"spread-turn-"+turning:"")}>
   {!singlePage&&(companion?<button className={"companion-page paper-"+(companion.pattern||"lined")+" side-"+(companionIndex%2?"right":"left")} style={{backgroundColor:companion.paperColor||"#fffdf7"}} onClick={()=>selectPage(companionIndex)}>
    <span className="companion-number">{companionIndex+1}</span>
    <div className="page-identity saved-identity"><label><span>Page name</span><em>{companion.pageName||`Page ${companionIndex+1}`}</em></label><label><span>Date</span><em>{companion.pageDate||"No date"}</em></label></div>
    <div className="date-row"><span>{companion.pageDate?new Intl.DateTimeFormat("en",{weekday:"long",month:"long",day:"numeric"}).format(new Date(companion.pageDate+"T12:00:00")):"Undated page"}</span><span className="mood">today’s mood ◡̈</span></div>
    <div className="journal-title saved-title">{companion.title}</div>
    <div className="content-grid"><div className={"writing-area font-"+(companion.font||"hand")}><div className="saved-note" style={{fontSize:companion.fontSize||18,color:companion.textColor||"#66564b"}}>{companion.note||"Write freely…"}</div></div>{companion.joysVisible!==false&&<div className="tiny-list saved-joys"><b>little joys</b>{(companion.joys||[]).map(j=><div className="saved-joy" key={j.id}>{j.done?"♥":"♡"} <span className={j.done?"done":""}>{j.text}</span></div>)}</div>}</div>
    <blockquote>“collect moments, not things”</blockquote>
    {companion.drawingData&&<img className="saved-drawing" src={companion.drawingData} alt=""/>}
    {(companion.photos||[]).map(p=><span key={p.id} className={"placed-photo saved-photo shape-"+(p.shape||"square")+(p.framed?" framed":"")} style={{left:p.x+"%",top:p.y+"%",width:p.size||180,zIndex:p.z,transform:`rotate(${p.rotation}deg)`}}><img src={p.src} alt=""/></span>)}
    {(companion.placed||[]).map(s=><span key={s.id} className="placed-sticker saved-sticker" style={{left:s.x+"%",top:s.y+"%",transform:`rotate(${s.rotation}deg)`}}>{s.value}</span>)}
   </button>:<button className={"companion-page blank-companion side-"+(companionIndex%2?"right":"left")} onClick={addPage}><Plus/><span>Add page {companionIndex+1}</span></button>)}
   <div className={"journal-page active-leaf side-"+(pageIndex%2?"right ":"left ")+"paper-"+pattern+" "+(drawing?"drawing-mode ":"")+(turning?"turn-"+turning:"")} style={{backgroundColor:paperColor}} ref={pageRef} onPointerMove={move} onPointerUp={()=>drag.current=null} onPointerLeave={()=>drag.current=null}>
    <div className="page-identity"><label><span>Page name</span><input value={pageName} onChange={e=>setPageName(e.target.value)} placeholder="Today, Dreams, Us…"/></label><label><span>Date</span><input type="date" value={pageDate} onChange={e=>setPageDate(e.target.value)}/></label></div>
    <div className="date-row"><span>{pageDate?new Intl.DateTimeFormat("en",{weekday:"long",month:"long",day:"numeric"}).format(new Date(pageDate+"T12:00:00")):"Undated page"}</span><span className="mood">today’s mood ◡̈</span></div>
    <input className="journal-title" value={title} onChange={e=>setTitle(e.target.value)}/>
    <div className="content-grid"><div className={"writing-area font-"+font}><Textarea style={{fontSize,color:textColor,"--journal-line-height":`${Math.max(32,Math.ceil(fontSize*1.55))}px`} as React.CSSProperties} value={note} onChange={e=>setNote(e.target.value)} placeholder={"Write freely…\n\nWhat made you smile today?\nWhat are you dreaming about?"}/></div>{joysVisible&&<div className="tiny-list"><button className="remove-joys" onClick={()=>setJoysVisible(false)} title="Remove Little Joys card">×</button><b>little joys</b>{joys.map(j=><div className="joy-row" key={j.id}><input type="checkbox" checked={j.done} onChange={()=>setJoys(a=>a.map(x=>x.id===j.id?{...x,done:!x.done}:x))}/><input value={j.text} className={j.done?"done":""} onChange={e=>setJoys(a=>a.map(x=>x.id===j.id?{...x,text:e.target.value}:x))}/><button onClick={()=>setJoys(a=>a.filter(x=>x.id!==j.id))}>×</button></div>)}<button className="add-joy" onClick={()=>setJoys(a=>[...a,{id:Date.now(),text:"new little joy",done:false}])}>+ add a joy</button></div>}</div><blockquote>“collect moments, not things”</blockquote>
    <canvas ref={canvasRef} className="drawing-canvas" onPointerDown={startDraw} onPointerMove={draw} onPointerUp={finishDrawing} onPointerLeave={finishDrawing}/>
    {photos.map(p=><button key={p.id} className={"placed-photo shape-"+(p.shape||"square")+" "+(p.framed?"framed ":"")+(selected===p.id?"selected":"")} style={{left:p.x+"%",top:p.y+"%",width:(p.size||180)+"px",transform:`rotate(${p.rotation}deg)`,zIndex:10+p.z}} onClick={()=>setSelected(p.id)} onPointerDown={e=>{setSelected(p.id);beginDrag(e,"photo",p.id)}}><img src={p.src} alt="Journal memory"/></button>)}
    {placed.map(s=><button key={s.id} className="placed-sticker" style={{left:s.x+"%",top:s.y+"%",transform:`rotate(${s.rotation}deg)`}} onDoubleClick={()=>setPlaced(p=>p.filter(x=>x.id!==s.id))} onPointerDown={e=>beginDrag(e,"sticker",s.id)}>{s.value}</button>)}
   </div></div><p className="hint">{drawing?"Draw directly on the page. Turn drawing off to move items.":"Tap either page to edit it. Move forward to open the next two pages."}</p>
  </section></div>
 </main>
}
