"use client";
import { useEffect,useRef,useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { BookOpen,Brush,ChevronLeft,ChevronRight,FileText,Focus,Frame,ImagePlus,Images,Layers,Palette,Plus,RotateCcw,Share2,Sparkles,Trash2,Type,X } from "lucide-react";

const stickers=["🌼","🍓","🎀","☁️","🪩","🦋","⭐","🍵","📚","🌙","💌","🧸"];
const themes=[{name:"Blush",color:"#df9b9b",pale:"#f8e9e5"},{name:"Sage",color:"#76947a",pale:"#e7eee3"},{name:"Sky",color:"#7897b5",pale:"#e5eef5"},{name:"Butter",color:"#c39b43",pale:"#f7efd6"},{name:"Lilac",color:"#907ba6",pale:"#eee8f3"}];
type Sticker={id:number;value:string;x:number;y:number;rotation:number};
type Photo={id:number;src:string;x:number;y:number;rotation:number;framed:boolean;z:number;size:number;shape:"square"|"round"|"soft"|"wavy"};
type Joy={id:number;text:string;done:boolean};
type PageData={id:number;pageName:string;pageDate:string;title:string;note:string;placed:Sticker[];photos:Photo[];drawingData:string;joys:Joy[];joysVisible:boolean;pattern:string;paperColor:string;font:string;fontSize:number;textColor:string};
type Drag={kind:"sticker"|"photo";id:number;dx:number;dy:number};

export default function Home(){
 const[screen,setScreen]=useState<"shelf"|"editor">("shelf"),[activeBook,setActiveBook]=useState("august"),[tool,setTool]=useState("write"),[focus,setFocus]=useState(false);
 const[turning,setTurning]=useState<""|"next"|"prev">("");
 const[singlePage,setSinglePage]=useState(false);
 const[books,setBooks]=useState([{id:"august",title:"My August Journal",tone:"rose",label:"summer notes"},{id:"wedding",title:"Wedding Memories",tone:"sage",label:"our story"},{id:"little",title:"Little Things",tone:"blue",label:"everyday magic"}]);
 const[note,setNote]=useState(""),[title,setTitle]=useState("Today, I want to remember…"),[theme,setTheme]=useState(themes[0]);
 const[placed,setPlaced]=useState<Sticker[]>([{id:1,value:"🌼",x:84,y:12,rotation:8},{id:2,value:"🎀",x:8,y:72,rotation:-8}]);
 const[photos,setPhotos]=useState<Photo[]>([]),[selected,setSelected]=useState<number|null>(null),[saved,setSaved]=useState(false);
 const[drawing,setDrawing]=useState(false),[penColor,setPenColor]=useState("#9c6868"),[drawingData,setDrawingData]=useState("");
 const[joys,setJoys]=useState<Joy[]>([{id:1,text:"slow mornings",done:false},{id:2,text:"good music",done:false},{id:3,text:"something sweet",done:false}]);
 const[joysVisible,setJoysVisible]=useState(true);
 const[pattern,setPattern]=useState("lined"),[paperColor,setPaperColor]=useState("#fffdf7"),[font,setFont]=useState("hand"),[fontSize,setFontSize]=useState(18),[textColor,setTextColor]=useState("#66564b");
 const[pages,setPages]=useState<PageData[]>([]),[pageIndex,setPageIndex]=useState(0);
 const[pageName,setPageName]=useState("Today"),[pageDate,setPageDate]=useState(new Date().toISOString().slice(0,10)),[pageSearch,setPageSearch]=useState("");
 const pageRef=useRef<HTMLDivElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),drag=useRef<Drag|null>(null),painting=useRef(false);
 useEffect(()=>{const q=window.matchMedia("(max-width: 650px)"),sync=()=>setSinglePage(q.matches);sync();q.addEventListener("change",sync);return()=>q.removeEventListener("change",sync)},[]);
 const resetBook=()=>{setPages([]);setPageIndex(0);setPageName("Today");setPageDate(new Date().toISOString().slice(0,10));setNote("");setTitle("Today, I want to remember…");setPlaced([]);setPhotos([]);setDrawingData("");setJoys([{id:1,text:"slow mornings",done:false},{id:2,text:"good music",done:false},{id:3,text:"something sweet",done:false}]);setJoysVisible(true);setPattern("lined");setPaperColor("#fffdf7");setFont("hand");setFontSize(18);setTextColor("#66564b");setTheme(themes[0]);setSelected(null)};
 const hydrate=(raw:string|null)=>{if(!raw){resetBook();return}try{const d=JSON.parse(raw);const first=d.pages?.[0]||d;if(!first){resetBook();return}setPages(d.pages||[]);setPageIndex(0);setPageName(first.pageName||"Today");setPageDate(first.pageDate||new Date().toISOString().slice(0,10));setNote(first.note||"");setTitle(first.title||"Today, I want to remember…");setPlaced(first.placed||[]);setPhotos(first.photos||(first.photo?[{id:Date.now(),src:first.photo,x:60,y:30,rotation:2,framed:true,z:1,size:180,shape:"square"}]:[]));setDrawingData(first.drawingData||"");setJoys(first.joys||[]);setJoysVisible(first.joysVisible!==false);setPattern(first.pattern||"lined");setPaperColor(first.paperColor||"#fffdf7");setFont(first.font||"hand");setFontSize(first.fontSize||18);setTextColor(first.textColor||"#66564b");setTheme(themes.find(t=>t.name===d.theme)||themes[0]);setSelected(null)}catch{resetBook()}};
 const openBook=(id:string)=>{setActiveBook(id);hydrate(localStorage.getItem(id==="august"?"pin-paper-journal":`pin-paper-journal-${id}`));setScreen("editor")};
 useEffect(()=>{const c=canvasRef.current,p=pageRef.current;if(!c||!p)return;const resize=()=>{c.width=p.clientWidth*devicePixelRatio;c.height=p.clientHeight*devicePixelRatio;c.style.width=p.clientWidth+"px";c.style.height=p.clientHeight+"px";const ctx=c.getContext("2d");ctx?.scale(devicePixelRatio,devicePixelRatio);if(drawingData){const im=new Image();im.onload=()=>ctx?.drawImage(im,0,0,p.clientWidth,p.clientHeight);im.src=drawingData}};resize();window.addEventListener("resize",resize);return()=>window.removeEventListener("resize",resize)},[drawingData]);
 const snapshot=():PageData=>({id:pages[pageIndex]?.id||Date.now(),pageName,pageDate,title,note,placed,photos,drawingData:canvasRef.current?.toDataURL()||drawingData,joys,joysVisible,pattern,paperColor,font,fontSize,textColor});
 const save=()=>{const next=pages.length?pages.map((p,i)=>i===pageIndex?snapshot():p):[snapshot()];setPages(next);setDrawingData(next[pageIndex].drawingData);localStorage.setItem(activeBook==="august"?"pin-paper-journal":`pin-paper-journal-${activeBook}`,JSON.stringify({pages:next,theme:theme.name}));setSaved(true);setTimeout(()=>setSaved(false),1600)};
 const loadPage=(p:PageData,i:number)=>{setPageIndex(i);setPageName(p.pageName||`Page ${i+1}`);setPageDate(p.pageDate||"");setTitle(p.title);setNote(p.note);setPlaced(p.placed);setPhotos(p.photos);setDrawingData(p.drawingData);setJoys(p.joys||[]);setJoysVisible(p.joysVisible!==false);setPattern(p.pattern);setPaperColor(p.paperColor);setFont(p.font);setFontSize(p.fontSize);setTextColor(p.textColor);setSelected(null)};
 const goPage=(i:number)=>{if(turning||i===pageIndex||i<0||i>=Math.max(1,pages.length))return;const next=pages.length?pages.map((p,n)=>n===pageIndex?snapshot():p):[snapshot()];setPages(next);setTurning(i>pageIndex?"next":"prev");window.setTimeout(()=>{loadPage(next[i],i);setTurning("")},360)};
 const selectPage=(i:number)=>{if(i===pageIndex||!pages[i])return;const next=pages.map((p,n)=>n===pageIndex?snapshot():p);setPages(next);loadPage(next[i],i)};
 const addPage=()=>{const current=pages.length?pages.map((p,i)=>i===pageIndex?snapshot():p):[snapshot()];const blank:PageData={id:Date.now(),pageName:`Page ${current.length+1}`,pageDate:new Date().toISOString().slice(0,10),title:"A fresh page…",note:"",placed:[],photos:[],drawingData:"",joys:[],joysVisible:true,pattern,paperColor,font,fontSize,textColor};const next=[...current,blank];setPages(next);loadPage(blank,next.length-1)};
 const sharePage=async()=>{const page=snapshot(),blob=new Blob([JSON.stringify(page)],{type:"application/json"}),file=new File([blob],`${title.replace(/[^a-z0-9]/gi,"-")||"journal-page"}.journal.json`,{type:"application/json"});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title,files:[file],text:"A page from my Pin & Paper journal"});else{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=file.name;a.click();URL.revokeObjectURL(a.href)}};
 const addSticker=(value:string)=>setPlaced(p=>[...p,{id:Date.now(),value,x:18+Math.random()*58,y:16+Math.random()*60,rotation:-10+Math.random()*20}]);
 const upload=(files:FileList|null)=>Array.from(files||[]).forEach((file,i)=>{const r=new FileReader();r.onload=()=>{const id=Date.now()+i;setPhotos(p=>[...p,{id,src:String(r.result),x:20+i*5,y:22+i*5,rotation:-4+i*3,framed:true,z:Math.max(0,...p.map(x=>x.z))+1,size:180,shape:"square"}]);setSelected(id)};r.readAsDataURL(file)});
 const move=(e:React.PointerEvent)=>{if(!drag.current||!pageRef.current||drawing)return;const b=pageRef.current.getBoundingClientRect(),x=Math.max(0,Math.min(88,((e.clientX-b.left-drag.current.dx)/b.width)*100)),y=Math.max(0,Math.min(84,((e.clientY-b.top-drag.current.dy)/b.height)*100));if(drag.current.kind==="sticker")setPlaced(a=>a.map(s=>s.id===drag.current?.id?{...s,x,y}:s));else setPhotos(a=>a.map(s=>s.id===drag.current?.id?{...s,x,y}:s))};
 const beginDrag=(e:React.PointerEvent,kind:Drag["kind"],id:number)=>{if(drawing)return;const b=e.currentTarget.getBoundingClientRect();drag.current={kind,id,dx:e.clientX-b.left,dy:e.clientY-b.top};e.currentTarget.setPointerCapture(e.pointerId)};
 const draw=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!painting.current)return;const c=e.currentTarget,b=c.getBoundingClientRect(),ctx=c.getContext("2d");if(!ctx)return;ctx.lineTo(e.clientX-b.left,e.clientY-b.top);ctx.strokeStyle=penColor;ctx.lineWidth=3;ctx.lineCap="round";ctx.lineJoin="round";ctx.stroke()};
 const startDraw=(e:React.PointerEvent<HTMLCanvasElement>)=>{painting.current=true;const b=e.currentTarget.getBoundingClientRect(),ctx=e.currentTarget.getContext("2d");ctx?.beginPath();ctx?.moveTo(e.clientX-b.left,e.clientY-b.top);e.currentTarget.setPointerCapture(e.pointerId)};
 const clearDrawing=()=>{const c=canvasRef.current;c?.getContext("2d")?.clearRect(0,0,c.width,c.height);setDrawingData("")};
 const editPhoto=(fn:(p:Photo)=>Photo)=>setPhotos(a=>a.map(p=>p.id===selected?fn(p):p));
 const active=photos.find(p=>p.id===selected);
 const spreadStart=Math.floor(pageIndex/2)*2,companionIndex=pageIndex===spreadStart?spreadStart+1:spreadStart,companion=pages[companionIndex];
 const previousTarget=singlePage?pageIndex-1:spreadStart-2;
 const nextTarget=singlePage?pageIndex+1:spreadStart+2;
 if(screen==="shelf")return <main className="library-screen"><div className="library-copy"><span className="eyebrow">PIN & PAPER</span><h1>Your little corner<br/>of memories</h1><p>Thoughts, photos and little joys — all in one place.</p></div><div className="shelf-scene"><div className="books-row">{books.map((b,i)=><button key={b.id} className={"book-cover "+b.tone} style={{"--tilt":`${i%2?2:-2}deg`} as React.CSSProperties} onClick={()=>openBook(b.id)}><span className="book-band">{b.label}</span><i>✦</i><strong>{b.title}</strong><small>2026</small></button>)}<button className="book-cover kraft new-book" onClick={()=>{const id="book-"+Date.now();setBooks(a=>[...a,{id,title:"Untitled Journal",tone:"kraft",label:"new memories"}]);openBook(id)}}><Plus/><strong>New journal</strong><small>make it yours</small></button></div><div className="wood-shelf"/></div><p className="library-hint">Choose a journal to begin</p></main>;
 return <main className={"desk-screen "+(focus?"focus-mode":"")} style={{"--ink":theme.color,"--wash":theme.pale} as React.CSSProperties}>
  <header className="topbar"><button className="back-library" onClick={()=>setScreen("shelf")}><BookOpen/> My journals</button><div className="page-nav"><Button variant="ghost" size="icon" disabled={previousTarget<0} onClick={()=>goPage(previousTarget)}><ChevronLeft/></Button><span>{singlePage?(pageName||`Page ${pageIndex+1}`):`Pages ${spreadStart+1}–${Math.min(spreadStart+2,Math.max(1,pages.length))}`}</span><Button variant="ghost" size="icon" disabled={nextTarget>=Math.max(1,pages.length)} onClick={()=>goPage(nextTarget)}><ChevronRight/></Button><Button variant="outline" size="sm" onClick={addPage}><Plus/> New page</Button></div><Button variant="ghost" size="icon" onClick={()=>setFocus(v=>!v)} title="Focus mode"><Focus/></Button><Button variant="outline" onClick={sharePage}><Share2/> Share</Button><Button onClick={save} className="save-button">{saved?"Saved quietly ♡":"Save"}</Button></header>
  <nav className="page-finder"><input value={pageSearch} onChange={e=>setPageSearch(e.target.value)} placeholder="Find by name or date…" aria-label="Search pages"/><div>{(pages.length?pages:[snapshot()]).map((p,i)=>({p,i})).filter(({p})=>(p.pageName||p.title||"").toLowerCase().includes(pageSearch.toLowerCase())||(p.pageDate||"").includes(pageSearch)).map(({p,i})=><button key={p.id} className={i===pageIndex?"active":""} onClick={()=>goPage(i)}><strong>{p.pageName||`Page ${i+1}`}</strong><small>{p.pageDate||"No date"}</small></button>)}<button onClick={addPage}><Plus/> New</button></div></nav>
  <div className="workspace"><nav className="page-tabs">{["Today","Dreams","Us","Ideas"].map((x,i)=><button key={x} className={i===pageIndex?"active":""} onClick={()=>i<pages.length&&goPage(i)}>{x}</button>)}<button onClick={addPage}>＋</button></nav><aside className="toolbox" data-tool={tool}><div className="tool-rail">{[{id:"write",icon:<Type/>,n:"Write"},{id:"photos",icon:<Images/>,n:"Photos"},{id:"stickers",icon:<Sparkles/>,n:"Stickers"},{id:"draw",icon:<Brush/>,n:"Draw"},{id:"paper",icon:<FileText/>,n:"Paper"}].map(t=><button key={t.id} className={tool===t.id?"active":""} onClick={()=>setTool(t.id)}>{t.icon}<span>{t.n}</span></button>)}</div><div className="tool-drawer"><button className="drawer-close" onClick={()=>setTool("")}><X/></button><div className="tape">creative drawer</div>
   <section className="tool-stickers"><h2><Sparkles size={16}/> Stickers & details</h2><p>Tap to drop one onto the page.</p><div className="sticker-grid">{stickers.map(s=><button key={s} onClick={()=>addSticker(s)}>{s}</button>)}</div></section>
   <section className="tool-paper"><h2><Palette size={16}/> Colour mood</h2><div className="swatches">{themes.map(t=><button key={t.name} onClick={()=>setTheme(t)} className={theme.name===t.name?"active":""} style={{background:t.color}} aria-label={t.name}/>)}</div><h2 className="subhead">Paper surface</h2><div className="compact-controls"><select value={pattern} onChange={e=>setPattern(e.target.value)}><option value="lined">Lined</option><option value="dots">Dotted</option><option value="grid">Grid</option><option value="plain">Plain</option></select><label>Paper <input type="color" value={paperColor} onChange={e=>setPaperColor(e.target.value)}/></label></div></section>
   <section className="tool-write"><h2>𝑨 Writing style</h2><div className="compact-controls"><select value={font} onChange={e=>setFont(e.target.value)}><option value="hand">Handwritten</option><option value="serif">Classic serif</option><option value="sans">Clean sans</option><option value="mono">Typewriter</option></select><label>Size <input type="range" min="12" max="34" value={fontSize} onChange={e=>setFontSize(+e.target.value)}/><b>{fontSize}</b></label><label>Ink <input type="color" value={textColor} onChange={e=>setTextColor(e.target.value)}/></label>{!joysVisible&&<Button variant="outline" size="sm" onClick={()=>setJoysVisible(true)}>＋ Add Little Joys card</Button>}</div></section>
   <section className="tool-photos"><h2><ImagePlus size={16}/> Photos</h2><p>Add several, then arrange them freely.</p><label className="upload"><input multiple type="file" accept="image/*" onChange={e=>upload(e.target.files)}/><ImagePlus size={18}/> Add pictures</label>
    {active&&<div className="photo-tools"><label className="size-control">Size <input type="range" min="80" max="420" value={active.size||180} onChange={e=>editPhoto(p=>({...p,size:+e.target.value}))}/></label><label className="size-control">Rotate <input type="range" min="-180" max="180" value={active.rotation} onChange={e=>editPhoto(p=>({...p,rotation:+e.target.value}))}/><b>{active.rotation}°</b></label><label className="shape-control">Shape <select value={active.shape||"square"} onChange={e=>editPhoto(p=>({...p,shape:e.target.value as Photo["shape"]}))}><option value="square">Square</option><option value="round">Circle</option><option value="soft">Soft corners</option><option value="wavy">Wavy</option></select></label><Button variant="outline" size="sm" onClick={()=>editPhoto(p=>({...p,framed:!p.framed}))}><Frame/> {active.framed?"Remove frame":"Add frame"}</Button><Button variant="outline" size="sm" onClick={()=>editPhoto(p=>({...p,z:Math.max(...photos.map(x=>x.z))+1}))}><Layers/> Bring front</Button><Button variant="outline" size="sm" onClick={()=>setPhotos(a=>a.filter(p=>p.id!==selected))}><Trash2/> Delete</Button></div>}
   </section>
   <section className="tool-draw"><h2><Brush size={16}/> Free drawing</h2><div className="draw-tools"><input type="color" value={penColor} onChange={e=>setPenColor(e.target.value)} aria-label="Pen colour"/><Button size="sm" variant={drawing?"default":"outline"} onClick={()=>setDrawing(v=>!v)}>{drawing?"Drawing on":"Start drawing"}</Button><Button size="sm" variant="ghost" onClick={clearDrawing}>Erase all</Button></div></section>
   <Button variant="ghost" className="clear-button" onClick={()=>{setPlaced([]);setPhotos([]);clearDrawing()}}><RotateCcw size={15}/> Clear decorations</Button>
  </div></aside>
  <section className="journal-shell">
   <div className={"book-spread "+(turning?"spread-turn-"+turning:"")}>
   {!singlePage&&(companion?<button className={"companion-page paper-"+(companion.pattern||"lined")+" side-"+(companionIndex%2?"right":"left")} style={{backgroundColor:companion.paperColor||"#fffdf7"}} onClick={()=>selectPage(companionIndex)}>
    <span className="companion-number">{companionIndex+1}</span>
    <div className="page-identity saved-identity"><label><span>Page name</span><em>{companion.pageName||`Page ${companionIndex+1}`}</em></label><label><span>Date</span><em>{companion.pageDate||"No date"}</em></label></div>
    <div className="date-row"><span>{companion.pageDate?new Intl.DateTimeFormat("en",{weekday:"long",month:"long",day:"numeric"}).format(new Date(companion.pageDate+"T12:00:00")):"Undated page"}</span><span className="mood">today’s mood ◡̈</span></div>
    <div className="journal-title saved-title">{companion.title}</div>
    <div className="content-grid"><div className={"writing-area font-"+(companion.font||"hand")}><div className="saved-note" style={{fontSize:companion.fontSize||18,color:companion.textColor||"#66564b"}}>{companion.note||"Write freely…"}</div></div>{companion.joysVisible!==false&&<div className="tiny-list saved-joys"><b>little joys</b>{(companion.joys||[]).map(j=><div className="saved-joy" key={j.id}>{j.done?"♥":"♡"} <span className={j.done?"done":""}>{j.text}</span></div>)}</div>}</div>
    <blockquote>“collect moments, not things”</blockquote>
    {companion.drawingData&&<img className="saved-drawing" src={companion.drawingData} alt=""/>}
    {(companion.photos||[]).map(p=><span key={p.id} className={"placed-photo saved-photo shape-"+(p.shape||"square")+(p.framed?" framed":"")} style={{left:p.x+"%",top:p.y+"%",width:p.size||180,zIndex:p.z,transform:`rotate(${p.rotation}deg)`}}><img src={p.src} alt=""/></span>)}
    {(companion.placed||[]).map(s=><span key={s.id} className="placed-sticker saved-sticker" style={{left:s.x+"%",top:s.y+"%",transform:`rotate(${s.rotation}deg)`}}>{s.value}</span>)}
   </button>:<button className={"companion-page blank-companion side-"+(companionIndex%2?"right":"left")} onClick={addPage}><Plus/><span>Add page {companionIndex+1}</span></button>)}
   <div className={"journal-page active-leaf side-"+(pageIndex%2?"right ":"left ")+"paper-"+pattern+" "+(drawing?"drawing-mode ":"")+(turning?"turn-"+turning:"")} style={{backgroundColor:paperColor}} ref={pageRef} onPointerMove={move} onPointerUp={()=>drag.current=null} onPointerLeave={()=>drag.current=null}>
    <div className="page-identity"><label><span>Page name</span><input value={pageName} onChange={e=>setPageName(e.target.value)} placeholder="Today, Dreams, Us…"/></label><label><span>Date</span><input type="date" value={pageDate} onChange={e=>setPageDate(e.target.value)}/></label></div>
    <div className="date-row"><span>{pageDate?new Intl.DateTimeFormat("en",{weekday:"long",month:"long",day:"numeric"}).format(new Date(pageDate+"T12:00:00")):"Undated page"}</span><span className="mood">today’s mood ◡̈</span></div>
    <input className="journal-title" value={title} onChange={e=>setTitle(e.target.value)}/>
    <div className="content-grid"><div className={"writing-area font-"+font}><Textarea style={{fontSize,color:textColor,"--journal-line-height":`${Math.max(32,Math.ceil(fontSize*1.55))}px`} as React.CSSProperties} value={note} onChange={e=>setNote(e.target.value)} placeholder={"Write freely…\n\nWhat made you smile today?\nWhat are you dreaming about?"}/></div>{joysVisible&&<div className="tiny-list"><button className="remove-joys" onClick={()=>setJoysVisible(false)} title="Remove Little Joys card">×</button><b>little joys</b>{joys.map(j=><div className="joy-row" key={j.id}><input type="checkbox" checked={j.done} onChange={()=>setJoys(a=>a.map(x=>x.id===j.id?{...x,done:!x.done}:x))}/><input value={j.text} className={j.done?"done":""} onChange={e=>setJoys(a=>a.map(x=>x.id===j.id?{...x,text:e.target.value}:x))}/><button onClick={()=>setJoys(a=>a.filter(x=>x.id!==j.id))}>×</button></div>)}<button className="add-joy" onClick={()=>setJoys(a=>[...a,{id:Date.now(),text:"new little joy",done:false}])}>+ add a joy</button></div>}</div><blockquote>“collect moments, not things”</blockquote>
    <canvas ref={canvasRef} className="drawing-canvas" onPointerDown={startDraw} onPointerMove={draw} onPointerUp={()=>painting.current=false} onPointerLeave={()=>painting.current=false}/>
    {photos.map(p=><button key={p.id} className={"placed-photo shape-"+(p.shape||"square")+" "+(p.framed?"framed ":"")+(selected===p.id?"selected":"")} style={{left:p.x+"%",top:p.y+"%",width:(p.size||180)+"px",transform:`rotate(${p.rotation}deg)`,zIndex:10+p.z}} onClick={()=>setSelected(p.id)} onPointerDown={e=>{setSelected(p.id);beginDrag(e,"photo",p.id)}}><img src={p.src} alt="Journal memory"/></button>)}
    {placed.map(s=><button key={s.id} className="placed-sticker" style={{left:s.x+"%",top:s.y+"%",transform:`rotate(${s.rotation}deg)`}} onDoubleClick={()=>setPlaced(p=>p.filter(x=>x.id!==s.id))} onPointerDown={e=>beginDrag(e,"sticker",s.id)}>{s.value}</button>)}
   </div></div><p className="hint">{drawing?"Draw directly on the page. Turn drawing off to move items.":"Tap either page to edit it. Move forward to open the next two pages."}</p>
  </section></div>
 </main>
}
