"use client";
/* eslint-disable @next/next/no-img-element -- Journal images are local data URLs; Next Image cannot optimize them. */
import { useEffect,useMemo,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { JournalLibrary } from "@/components/journal-library";
import { AppNotice } from "@/components/app-notice";
import { StickerCatalog, type CatalogSticker } from "@/components/sticker-catalog";
import { JournalTemplateLayer } from "@/components/journal-template";
import type { Book, FreeText, JournalTemplate, Joy, MoodEntry, PageData, Photo, Sticker, TodoItem } from "@/lib/journal-model";
import { PageFinder } from "@/components/page-finder";
import { compressImage, processImageBatch, readFileAsDataUrl } from "@/lib/image-compression";
import { createEncryptedJournal, deleteEncryptedJournal, listEncryptedJournals, updateEncryptedJournal } from "@/lib/journal-repository";
import { clearPersistedAccountMasterKey, getAccountMasterKey, hasAccountMasterKey, restoreAccountMasterKey } from "@/lib/key-vault";
import { createClient } from "@/lib/supabase/client";
import { markCloudDraftSynced, readCloudDraft, writeCloudDraft } from "@/lib/cloud-drafts";
import { makeBackup, parseBackup } from "@/lib/local-backup";
import { downloadMigrationBackup, getLocalMigrationSources, migrateLocalJournals, removeMigratedLocalCopies, type MigrationSource } from "@/lib/local-migration";
import { loadEncryptedPages, reloadEncryptedAsset, syncEncryptedPages } from "@/lib/page-repository";
import { repairEncryptedPhotos } from "@/lib/page-repository";
import { revokeAllEncryptedAssetUrls, revokeEncryptedAssetUrl } from "@/lib/asset-repository";
import { readOperationalEvents, recordOperationalEvent, subscribeToOperationalEvents, type OperationalEvent } from "@/lib/error-monitoring";
import { moveItem, removeItem } from "@/lib/page-order";
import { isOfflineSyncError, OFFLINE_DRAFT_MESSAGE } from "@/lib/sync-errors";
import { exportJournalPage } from "@/lib/page-export";
import { downloadBackupFile, importCloudBackup, makeCloudBackup } from "@/lib/cloud-backup";
import { clampJournalPosition, pageScaledPixels, photoSizePercent } from "@/lib/journal-layout";
import { useDebouncedEffect } from "@/lib/use-debounced-effect";
import { journalChangeSignature } from "@/lib/journal-change-signature";
import { ArrowLeft,ArrowRight,BookOpen,Brush,ChevronLeft,ChevronRight,FileText,Focus,Frame,History,ImagePlus,Images,Layers,Palette,Plus,Redo2,RotateCcw,Share2,Sparkles,Trash2,Type,Undo2,X } from "lucide-react";

const themes=[{name:"Blush",color:"#df9b9b",pale:"#f8e9e5"},{name:"Sage",color:"#76947a",pale:"#e7eee3"},{name:"Sky",color:"#7897b5",pale:"#e5eef5"},{name:"Butter",color:"#c39b43",pale:"#f7efd6"},{name:"Lilac",color:"#907ba6",pale:"#eee8f3"}];
const penPalette=["#5b4b43","#a96f69","#d79b9b","#d9bd72","#91a58f","#86a7b2","#9485a7","#b5917f"];
const paperModes=[{name:"Pure white",color:"#ffffff"},{name:"Soft ivory",color:"#fffaf0"},{name:"Enzo",color:"#e8dfd0"},{name:"Midnight black",color:"#11100f"}];
const DEFAULT_TEMPLATE_LAYOUT={x:12,y:31,width:79,height:57};
const DEFAULT_TEMPLATE_TITLES:Record<JournalTemplate,string>={free:"",habit:"Habit tracker",mood:"Mood tracker",weekly:"Weekly plan",todo:"To-do list"};
type PenType="fine"|"pencil"|"highlighter"|"brush";
type Drag={kind:"sticker"|"photo"|"joy"|"text"|"template";id:number;dxPercent:number;dyPercent:number;widthPercent:number;heightPercent:number};
const DEFAULT_BOOKS:Book[]=[{id:"august",title:"My August Journal",tone:"rose",label:"summer notes"},{id:"wedding",title:"Wedding Memories",tone:"sage",label:"our story"},{id:"little",title:"Little Things",tone:"blue",label:"everyday magic"}];
const BOOKS_STORAGE_KEY="pin-paper-journal-books";
const storageKey=(bookId:string)=>bookId==="august"?"pin-paper-journal":`pin-paper-journal-${bookId}`;

export default function Home({ cloudUserId }: { cloudUserId?: string }){
 const router=useRouter();
 const isCloud=Boolean(cloudUserId);
 const[screen,setScreen]=useState<"shelf"|"editor">("shelf"),[activeBook,setActiveBook]=useState("august"),[tool,setTool]=useState("write"),[focus,setFocus]=useState(false),[pagePanelOpen,setPagePanelOpen]=useState(false);
 const[turning,setTurning]=useState<""|"next"|"prev">("");
 const[singlePage,setSinglePage]=useState(false);
 const[books,setBooks]=useState<Book[]>(isCloud?[]:DEFAULT_BOOKS),[libraryBusy,setLibraryBusy]=useState(isCloud),[libraryMessage,setLibraryMessage]=useState(""),[migrationSources,setMigrationSources]=useState<MigrationSource[]>([]),[migrationBusy,setMigrationBusy]=useState(false),[migratedLocalIds,setMigratedLocalIds]=useState<string[]>([]);
 const[note,setNote]=useState(""),[title,setTitle]=useState("Today, I want to remember…"),[theme,setTheme]=useState(themes[0]);
 const[placed,setPlaced]=useState<Sticker[]>([{id:1,value:"🌼",x:84,y:12,rotation:8},{id:2,value:"🎀",x:8,y:72,rotation:-8}]);
 const[selectedSticker,setSelectedSticker]=useState<number|null>(null),[freeTexts,setFreeTexts]=useState<FreeText[]>([]),[selectedText,setSelectedText]=useState<number|null>(null);
 const[photos,setPhotos]=useState<Photo[]>([]),[selected,setSelected]=useState<number|null>(null),[saveState,setSaveState]=useState<"idle"|"saving"|"saved"|"offline"|"error">("idle"),[saveError,setSaveError]=useState(""),[assetProgress,setAssetProgress]=useState<{completed:number;total:number}|null>(null);
 const[repairingPhotos,setRepairingPhotos]=useState<Set<number>>(new Set());
 const[syncHistoryOpen,setSyncHistoryOpen]=useState(false),[syncEvents,setSyncEvents]=useState<OperationalEvent[]>([]);
 const[drawing,setDrawing]=useState(false),[penColor,setPenColor]=useState("#5b4b43"),[penType,setPenType]=useState<PenType>("fine"),[drawingData,setDrawingData]=useState(""),[drawingAssetId,setDrawingAssetId]=useState<string|undefined>();
 const[joys,setJoys]=useState<Joy[]>([{id:1,text:"slow mornings",done:false},{id:2,text:"good music",done:false},{id:3,text:"something sweet",done:false}]);
 const[joysVisible,setJoysVisible]=useState(true);
 const[joyPosition,setJoyPosition]=useState({x:53,y:61});
 const[joyTitle,setJoyTitle]=useState("little joys"),[joyColor,setJoyColor]=useState("#eee2a9"),[joyTextColor,setJoyTextColor]=useState("#66564b");
 const[template,setTemplate]=useState<JournalTemplate>("free"),[templateTitle,setTemplateTitle]=useState(""),[trackerChecks,setTrackerChecks]=useState<boolean[]>([]),[todoItems,setTodoItems]=useState<TodoItem[]>([]),[moodEntries,setMoodEntries]=useState<MoodEntry[]>([]),[templateLayout,setTemplateLayout]=useState(DEFAULT_TEMPLATE_LAYOUT);
 const[pattern,setPattern]=useState("lined"),[paperColor,setPaperColor]=useState("#fffdf7"),[font,setFont]=useState("hand"),[fontSize,setFontSize]=useState(18),[textColor,setTextColor]=useState("#66564b");
 const[paperScope,setPaperScope]=useState<"page"|"journal">("page");
 const[pages,setPages]=useState<PageData[]>([]),[pageIndex,setPageIndex]=useState(0);
 const[pageName,setPageName]=useState("Today"),[pageDate,setPageDate]=useState(new Date().toISOString().slice(0,10)),[pageSearch,setPageSearch]=useState("");
 const[canUndo,setCanUndo]=useState(false),[canRedo,setCanRedo]=useState(false);
 const pageRef=useRef<HTMLDivElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),drag=useRef<Drag|null>(null),painting=useRef(false),hydratedBook=useRef("");
 const history=useRef<{pageId:string|number|null;past:string[];present:string;future:string[]}>({pageId:null,past:[],present:"",future:[]});
 const syncQueue=useRef<Promise<void>>(Promise.resolve()),syncRequest=useRef(0),pagehidePersist=useRef<()=>void>(()=>undefined),lastPersisted=useRef({book:"",signature:""});
 useEffect(()=>{const q=window.matchMedia("(max-width: 650px)"),sync=()=>{setSinglePage(q.matches);if(q.matches)setTool("")};sync();q.addEventListener("change",sync);return()=>q.removeEventListener("change",sync)},[]);
 useEffect(()=>()=>revokeAllEncryptedAssetUrls(),[]);
 useEffect(()=>{const refresh=()=>setSyncEvents(readOperationalEvents("sync").slice(-12).reverse());refresh();return subscribeToOperationalEvents(refresh)},[]);
 useEffect(()=>{if(isCloud)return;let cancelled=false;try{const raw=localStorage.getItem(BOOKS_STORAGE_KEY);if(raw){const parsed=JSON.parse(raw);if(Array.isArray(parsed)&&parsed.length)queueMicrotask(()=>{if(!cancelled)setBooks(parsed)})}}catch{/* Keep the built-in shelf if old data is malformed. */}return()=>{cancelled=true}},[isCloud]);
 useEffect(()=>{if(!isCloud||!cloudUserId)return;let cancelled=false;const load=async()=>{setLibraryBusy(true);try{if(!hasAccountMasterKey()&&!await restoreAccountMasterKey(cloudUserId)){router.replace("/");return}const loaded=await listEncryptedJournals(getAccountMasterKey());if(!cancelled){setBooks(loaded);setMigrationSources(getLocalMigrationSources());setLibraryMessage(loaded.length?"Your encrypted journals are synced.":"Create your first encrypted journal.")}}catch(error){if(!cancelled)setLibraryMessage(error instanceof Error?error.message:"Your encrypted journals could not be loaded.")}finally{if(!cancelled)setLibraryBusy(false)}};void load();return()=>{cancelled=true}},[isCloud,cloudUserId,router]);
 const resetBook=()=>{setPages([]);setPageIndex(0);setPageName("Today");setPageDate(new Date().toISOString().slice(0,10));setNote("");setTitle("Today, I want to remember…");setPlaced([]);setPhotos([]);setFreeTexts([]);setTemplate("free");setTemplateTitle("");setTrackerChecks([]);setTodoItems([]);setMoodEntries([]);setTemplateLayout(DEFAULT_TEMPLATE_LAYOUT);setDrawingData("");setDrawingAssetId(undefined);setJoys([{id:1,text:"slow mornings",done:false},{id:2,text:"good music",done:false},{id:3,text:"something sweet",done:false}]);setJoysVisible(true);setJoyPosition({x:53,y:61});setJoyTitle("little joys");setJoyColor("#eee2a9");setJoyTextColor("#66564b");setPattern("lined");setPaperColor("#fffdf7");setFont("hand");setFontSize(18);setTextColor("#66564b");setTheme(themes[0]);setSelected(null);setSelectedSticker(null);setSelectedText(null)};
 const hydrate=(raw:string|null)=>{if(!raw){resetBook();return}try{const d=JSON.parse(raw);const first=d.pages?.[0]||d;if(!first){resetBook();return}setPages(d.pages||[]);setPageIndex(0);setPageName(first.pageName||"Today");setPageDate(first.pageDate||new Date().toISOString().slice(0,10));setNote(first.note||"");setTitle(first.title||"Today, I want to remember…");setPlaced(first.placed||[]);setPhotos(first.photos||(first.photo?[{id:1,src:first.photo,x:60,y:30,rotation:2,framed:true,z:1,size:180,shape:"square"}]:[]));setFreeTexts(first.freeTexts||[]);setTemplate(first.template||"free");setTemplateTitle(first.templateTitle||DEFAULT_TEMPLATE_TITLES[first.template as JournalTemplate]||"");setTrackerChecks(first.trackerChecks||[]);setTodoItems(first.todoItems||[]);setMoodEntries(first.moodEntries||[]);setTemplateLayout(first.templateLayout||DEFAULT_TEMPLATE_LAYOUT);setDrawingData(first.drawingData||"");setDrawingAssetId(first.drawingAssetId);setJoys(first.joys||[]);setJoysVisible(first.joysVisible!==false);setJoyPosition(first.joyPosition||{x:53,y:61});setJoyTitle(first.joyTitle||"little joys");setJoyColor(first.joyColor||"#eee2a9");setJoyTextColor(first.joyTextColor||"#66564b");setPattern(first.pattern||"lined");setPaperColor(first.paperColor||"#fffdf7");setFont(first.font||"hand");setFontSize(first.fontSize||18);setTextColor(first.textColor||"#66564b");setTheme(themes.find(t=>t.name===d.theme)||themes[0]);setSelected(null);setSelectedSticker(null);setSelectedText(null)}catch{resetBook()}};
 const openBook=async(id:string)=>{revokeAllEncryptedAssetUrls();history.current={pageId:null,past:[],present:"",future:[]};setCanUndo(false);setCanRedo(false);setActiveBook(id);setSaveState(isCloud?"saving":"idle");setSaveError("");setScreen("editor");if(!isCloud){hydrate(localStorage.getItem(storageKey(id)));hydratedBook.current=id;return}const draft=readCloudDraft(id);if(draft?.pendingSync){hydrate(JSON.stringify(draft));hydratedBook.current=id;setSaveError("Offline changes are safe on this device and waiting to sync.");void queueCloudSync(id,draft.pages,draft.theme,true);return}try{const loaded=await loadEncryptedPages(getAccountMasterKey(),id);if(loaded.pages.length)hydrate(JSON.stringify({pages:loaded.pages,theme:"Blush"}));else resetBook();hydratedBook.current=id;setSaveState("saved")}catch(error){if(draft){hydrate(JSON.stringify(draft));hydratedBook.current=id}setSaveState("error");setSaveError(error instanceof Error?error.message:"Encrypted pages could not be loaded.")}};
 useEffect(()=>{const c=canvasRef.current,p=pageRef.current;if(!c||!p)return;const resize=()=>{c.width=p.clientWidth*devicePixelRatio;c.height=p.clientHeight*devicePixelRatio;c.style.width=p.clientWidth+"px";c.style.height=p.clientHeight+"px";const ctx=c.getContext("2d");ctx?.scale(devicePixelRatio,devicePixelRatio);if(drawingData){const im=new Image();im.onload=()=>ctx?.drawImage(im,0,0,p.clientWidth,p.clientHeight);im.src=drawingData}};resize();window.addEventListener("resize",resize);return()=>window.removeEventListener("resize",resize)},[drawingData]);
 const snapshot=():PageData=>({id:pages[pageIndex]?.id||crypto.randomUUID(),pageName,pageDate,title,note,placed,photos,drawingData,drawingAssetId,joys,joysVisible,joyPosition,joyTitle,joyColor,joyTextColor,template,templateTitle,trackerChecks,todoItems,moodEntries,templateLayout,freeTexts,pattern,paperColor,font,fontSize,textColor});
 const applyPaperColor=(color:string)=>{const dark=color==="#11100f",ink=dark?"#fffaf0":paperColor==="#11100f"?"#66564b":textColor;setPaperColor(color);setTextColor(ink);if(paperScope==="journal"){const current=pages.length?pages.map((page,index)=>index===pageIndex?snapshot():page):[snapshot()];setPages(current.map(page=>({...page,paperColor:color,textColor:dark?"#fffaf0":page.paperColor==="#11100f"?"#66564b":page.textColor})))}};
 const applyPaperPattern=(next:string)=>{const retro=next==="retro";setPattern(next);if(retro){setPaperColor("#d8aa73");setTextColor("#4b3426")}if(paperScope==="journal"){const current=pages.length?pages.map((page,index)=>index===pageIndex?snapshot():page):[snapshot()];setPages(current.map(page=>({...page,pattern:next,...(retro?{paperColor:"#d8aa73",textColor:"#4b3426"}:{})})))}};
 const queueCloudSync=(journalId:string,next:PageData[],themeName:string,quiet=false)=>{
  if(!cloudUserId)return Promise.resolve();
  const request=++syncRequest.current;
  if(!quiet)setSaveState("saving");
  recordOperationalEvent("sync","started");
  syncQueue.current=syncQueue.current.catch(()=>undefined).then(async()=>{
   if(!navigator.onLine)throw new TypeError("Offline");
   const synced=await syncEncryptedPages({userId:cloudUserId,journalId,masterKey:getAccountMasterKey(),pages:next,onAssetProgress:(completed,total)=>{if(request===syncRequest.current)setAssetProgress({completed,total})}});
   if(request===syncRequest.current){
    const assetIds=new Map(synced.flatMap(page=>page.photos.filter(photo=>photo.assetId).map(photo=>[photo.id,photo.assetId] as const)));
    const attachAssetIds=(items:Photo[])=>items.map(photo=>assetIds.has(photo.id)?{...photo,assetId:assetIds.get(photo.id)}:photo);
    setPhotos(attachAssetIds);
    setPages(existing=>existing.map(page=>({...page,photos:attachAssetIds(page.photos)})));
    markCloudDraftSynced(journalId,synced,themeName);setAssetProgress(null);setSaveState("saved");setSaveError("");recordOperationalEvent("sync","success");
   }
  }).catch(error=>{
   if(request===syncRequest.current){
    setAssetProgress(null);
    if(isOfflineSyncError(error)){setSaveState("offline");setSaveError(OFFLINE_DRAFT_MESSAGE);recordOperationalEvent("sync","offline",error)}
    else{setSaveState("error");setSaveError("Cloud sync could not finish. Your local draft is safe.");recordOperationalEvent("sync","failure",error)}
   }
  });
  return syncQueue.current
 };
 const persistPages=(next:PageData[],manual=false)=>{try{if(isCloud){writeCloudDraft(activeBook,next,theme.name,true);lastPersisted.current={book:activeBook,signature:journalChangeSignature(next,theme.name)};void queueCloudSync(activeBook,next,theme.name,!manual)}else{localStorage.setItem(storageKey(activeBook),JSON.stringify({version:1,pages:next,theme:theme.name,updatedAt:new Date().toISOString()}));lastPersisted.current={book:activeBook,signature:journalChangeSignature(next,theme.name)};if(manual)setSaveState("saved")}return true}catch(error){setSaveState("error");setSaveError(error instanceof DOMException&&error.name==="QuotaExceededError"?"Browser storage is full. Remove some photos or export this page before leaving.":"This journal could not be saved. Please keep this tab open and try again.");return false}};
 const save=()=>{setSaveState("saving");const next=pages.length?pages.map((p,i)=>i===pageIndex?snapshot():p):[snapshot()];setPages(next);setDrawingData(next[pageIndex].drawingData);return persistPages(next,true)};
 useEffect(()=>{if(screen!=="editor")return;const persist=()=>pagehidePersist.current();window.addEventListener("pagehide",persist);return()=>window.removeEventListener("pagehide",persist)},[screen,activeBook]);
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!isCloud)return;const retry=()=>{const draft=readCloudDraft(activeBook);if(screen==="editor"&&draft?.pendingSync)void queueCloudSync(activeBook,draft.pages,draft.theme,true)};window.addEventListener("online",retry);return()=>window.removeEventListener("online",retry)},[isCloud,activeBook,screen]);
 const loadPage=(p:PageData,i:number)=>{setPageIndex(i);setPageName(p.pageName||`Page ${i+1}`);setPageDate(p.pageDate||"");setTitle(p.title);setNote(p.note);setPlaced(p.placed);setPhotos(p.photos);setFreeTexts(p.freeTexts||[]);setTemplate(p.template||"free");setTemplateTitle(p.templateTitle||DEFAULT_TEMPLATE_TITLES[p.template||"free"]);setTrackerChecks(p.trackerChecks||[]);setTodoItems(p.todoItems||[]);setMoodEntries(p.moodEntries||[]);setTemplateLayout(p.templateLayout||DEFAULT_TEMPLATE_LAYOUT);setDrawingData(p.drawingData);setDrawingAssetId(p.drawingAssetId);setJoys(p.joys||[]);setJoysVisible(p.joysVisible!==false);setJoyPosition(p.joyPosition||{x:53,y:61});setJoyTitle(p.joyTitle||"little joys");setJoyColor(p.joyColor||"#eee2a9");setJoyTextColor(p.joyTextColor||"#66564b");setPattern(p.pattern);setPaperColor(p.paperColor);setFont(p.font);setFontSize(p.fontSize);setTextColor(p.textColor);setSelected(null);setSelectedSticker(null);setSelectedText(null)};
 const goPage=(i:number)=>{if(turning||i===pageIndex||i<0||i>=Math.max(1,pages.length))return;const next=pages.length?pages.map((p,n)=>n===pageIndex?snapshot():p):[snapshot()];setPages(next);setTurning(i>pageIndex?"next":"prev");window.setTimeout(()=>{loadPage(next[i],i);setTurning("")},360)};
 const selectPage=(i:number)=>{if(i===pageIndex||!pages[i])return;const next=pages.map((p,n)=>n===pageIndex?snapshot():p);setPages(next);loadPage(next[i],i)};
 const addPage=()=>{const current=pages.length?pages.map((p,i)=>i===pageIndex?snapshot():p):[snapshot()];const blank:PageData={id:crypto.randomUUID(),pageName:`Page ${current.length+1}`,pageDate:new Date().toISOString().slice(0,10),title:"A fresh page…",note:"",placed:[],photos:[],freeTexts:[],template:"free",templateTitle:"",trackerChecks:[],todoItems:[],moodEntries:[],templateLayout:DEFAULT_TEMPLATE_LAYOUT,drawingData:"",joys:[],joysVisible:true,joyPosition:{x:53,y:61},joyTitle:"little joys",joyColor:"#eee2a9",joyTextColor:"#66564b",pattern,paperColor,font,fontSize,textColor};const next=[...current,blank];setPages(next);loadPage(blank,next.length-1)};
 const deletePage=()=>{if(!window.confirm(`Delete “${pageName||`Page ${pageIndex+1}`}”? This cannot be undone.`))return;const current=pages.length?pages.map((p,i)=>i===pageIndex?snapshot():p):[snapshot()];if(current.length===1){resetBook();history.current={pageId:null,past:[],present:"",future:[]};return}const next=removeItem(current,pageIndex),nextIndex=Math.min(pageIndex,next.length-1);setPages(next);loadPage(next[nextIndex],nextIndex)};
 const movePage=(direction:-1|1)=>{const target=pageIndex+direction;if(target<0||target>=Math.max(1,pages.length))return;const current=pages.length?pages.map((p,i)=>i===pageIndex?snapshot():p):[snapshot()],next=moveItem(current,pageIndex,target);setPages(next);loadPage(next[target],target)};
 const sharePage=async()=>{try{await exportJournalPage(snapshot(),title);setSaveError("")}catch(error){setSaveError(error instanceof Error?`Page export failed: ${error.message}`:"The page could not be exported.")}};
 const addSticker=(item:CatalogSticker,position?:{x:number;y:number})=>{const id=Date.now();setPlaced(items=>[...items,{id,value:item.value,category:item.category,kind:item.kind||"sticker",x:position?.x??18+Math.random()*58,y:position?.y??16+Math.random()*60,rotation:item.kind==="tape"?-2:-10+Math.random()*20,size:item.kind==="tape"?190:52,z:Math.max(0,...items.map(entry=>entry.z||0))+1,opacity:item.kind==="tape"?.82:1}]);setSelectedSticker(id);setSelected(null);setSelectedText(null)};
 const addFreeText=()=>{const id=Date.now();setFreeTexts(items=>[...items,{id,text:"Write anywhere…",x:28,y:42,rotation:0,size:18,z:Math.max(0,...items.map(item=>item.z))+1}]);setSelectedText(id);setSelectedSticker(null);setSelected(null)};
 const dropCatalogSticker=(event:React.DragEvent<HTMLDivElement>)=>{event.preventDefault();const raw=event.dataTransfer.getData("application/x-journal-sticker");if(!raw)return;try{const item=JSON.parse(raw) as CatalogSticker,bounds=event.currentTarget.getBoundingClientRect();addSticker(item,{x:clampJournalPosition((event.clientX-bounds.left)/bounds.width*100,15),y:clampJournalPosition((event.clientY-bounds.top)/bounds.height*100,10)})}catch{/* Ignore malformed external drag data. */}};
 const upload=async(files:FileList|null)=>{await processImageBatch(Array.from(files||[]),async(file,i)=>{try{const compressed=await compressImage(file),src=await readFileAsDataUrl(compressed),id=Date.now()+i;setPhotos(p=>[...p,{id,src,x:20+i*5,y:22+i*5,rotation:-4+i*3,framed:true,z:Math.max(0,...p.map(x=>x.z))+1,size:180,shape:"square"}]);setSelected(id);setSaveError("")}catch(error){setSaveError(error instanceof Error?error.message:`${file.name} could not be added.`)}})};
 const move=(e:React.PointerEvent)=>{if(!drag.current||!pageRef.current||drawing)return;const b=pageRef.current.getBoundingClientRect(),x=clampJournalPosition(((e.clientX-b.left)/b.width)*100-drag.current.dxPercent,drag.current.widthPercent),y=clampJournalPosition(((e.clientY-b.top)/b.height)*100-drag.current.dyPercent,drag.current.heightPercent);if(drag.current.kind==="sticker")setPlaced(a=>a.map(s=>s.id===drag.current?.id?{...s,x,y}:s));else if(drag.current.kind==="photo")setPhotos(a=>a.map(s=>s.id===drag.current?.id?{...s,x,y}:s));else if(drag.current.kind==="text")setFreeTexts(a=>a.map(s=>s.id===drag.current?.id?{...s,x,y}:s));else if(drag.current.kind==="template")setTemplateLayout(layout=>({...layout,x,y}));else setJoyPosition({x,y})};
 const beginDrag=(e:React.PointerEvent,kind:Drag["kind"],id:number)=>{if(drawing||!pageRef.current)return;const target=kind==="template"?e.currentTarget.parentElement:e.currentTarget;if(!target)return;const item=target.getBoundingClientRect(),page=pageRef.current.getBoundingClientRect();drag.current={kind,id,dxPercent:((e.clientX-item.left)/page.width)*100,dyPercent:((e.clientY-item.top)/page.height)*100,widthPercent:(item.width/page.width)*100,heightPercent:(item.height/page.height)*100};e.currentTarget.setPointerCapture(e.pointerId)};
 const configurePen=(ctx:CanvasRenderingContext2D)=>{ctx.strokeStyle=penColor;ctx.lineWidth=penType==="fine"?2:penType==="pencil"?3:penType==="highlighter"?16:7;ctx.globalAlpha=penType==="highlighter"?.28:penType==="pencil"?.62:1;ctx.lineCap=penType==="highlighter"?"butt":"round";ctx.lineJoin="round"};
 const draw=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!painting.current)return;const c=e.currentTarget,b=c.getBoundingClientRect(),ctx=c.getContext("2d");if(!ctx)return;configurePen(ctx);ctx.lineTo(e.clientX-b.left,e.clientY-b.top);ctx.stroke()};
 const startDraw=(e:React.PointerEvent<HTMLCanvasElement>)=>{painting.current=true;const b=e.currentTarget.getBoundingClientRect(),ctx=e.currentTarget.getContext("2d");if(ctx){configurePen(ctx);ctx.beginPath();ctx.moveTo(e.clientX-b.left,e.clientY-b.top)}e.currentTarget.setPointerCapture(e.pointerId)};
 const clearDrawing=()=>{const c=canvasRef.current;c?.getContext("2d")?.clearRect(0,0,c.width,c.height);setDrawingData("");setDrawingAssetId(undefined)};
 const finishDrawing=()=>{painting.current=false;setDrawingData(canvasRef.current?.toDataURL()||"");setDrawingAssetId(undefined)};
 const editPhoto=(fn:(p:Photo)=>Photo)=>setPhotos(a=>a.map(p=>p.id===selected?fn(p):p));
 const clearDecorations=()=>{photos.forEach(photo=>revokeEncryptedAssetUrl(photo.src));setPlaced([]);setPhotos([]);setSelected(null);clearDrawing()};
 const repairPhoto=async(photo:Photo)=>{if(!isCloud||!photo.assetId||repairingPhotos.has(photo.id))return;setRepairingPhotos(current=>new Set(current).add(photo.id));try{const src=await reloadEncryptedAsset(getAccountMasterKey(),activeBook,photo.assetId);revokeEncryptedAssetUrl(photo.src);setPhotos(items=>items.map(item=>item.id===photo.id?{...item,src,loadError:undefined}:item));setSaveError("")}catch(error){const message=error instanceof Error?error.message:"This photo could not be reopened.";setPhotos(items=>items.map(item=>item.id===photo.id?{...item,src:"",loadError:message}:item));setSaveError(`Photo could not be reopened: ${message}`)}finally{setRepairingPhotos(current=>{const next=new Set(current);next.delete(photo.id);return next})}};
 const repairAllPhotos=async()=>{if(!isCloud)return;const currentPages=pages.length?pages.map((page,index)=>index===pageIndex?snapshot():page):[snapshot()];const targets=currentPages.reduce((total,page)=>total+page.photos.filter(photo=>photo.assetId&&(!photo.src||photo.loadError)).length,0);if(!targets)return;setAssetProgress({completed:0,total:targets});let completed=0;const repaired=[] as PageData[];for(const page of currentPages){const nextPhotos=await repairEncryptedPhotos(getAccountMasterKey(),activeBook,page.photos);completed+=page.photos.filter(photo=>photo.assetId&&(!photo.src||photo.loadError)).length;setAssetProgress({completed,total:targets});repaired.push({...page,photos:nextPhotos})}setPages(repaired);loadPage(repaired[pageIndex],pageIndex);setAssetProgress(null);const remaining=repaired.reduce((total,page)=>total+page.photos.filter(photo=>photo.loadError).length,0);setSaveError(remaining?`${remaining} photo${remaining===1?"":"s"} could not be restored. The encrypted file may be missing.`:"")};
 const active=photos.find(p=>p.id===selected);
 const activeSticker=placed.find(item=>item.id===selectedSticker),activeText=freeTexts.find(item=>item.id===selectedText);
 const brokenPhotoCount=photos.filter(photo=>photo.assetId&&(!photo.src||photo.loadError)).length;
 const spreadStart=Math.floor(pageIndex/2)*2,companionIndex=pageIndex===spreadStart?spreadStart+1:spreadStart,companion=pages[companionIndex];
 const previousTarget=singlePage?pageIndex-1:spreadStart-2;
 const nextTarget=singlePage?pageIndex+1:spreadStart+2;
 const currentPreview:PageData={id:pages[pageIndex]?.id||0,pageName,pageDate,title,note,placed,photos,drawingData,drawingAssetId,joys,joysVisible,joyPosition,joyTitle,joyColor,joyTextColor,template,templateTitle,trackerChecks,todoItems,moodEntries,templateLayout,freeTexts,pattern,paperColor,font,fontSize,textColor};
 const currentSerialized=JSON.stringify(currentPreview);
 const autoSavePages=useMemo(()=>{const preview=JSON.parse(currentSerialized) as PageData;return pages.length?pages.map((page,index)=>index===pageIndex?preview:page):[preview]},[pages,pageIndex,currentSerialized]);
 const autoSaveSignature=journalChangeSignature(autoSavePages,theme.name);
 useEffect(()=>{if(screen!=="editor"||hydratedBook.current!==activeBook)return;pagehidePersist.current=()=>{try{if(isCloud)writeCloudDraft(activeBook,autoSavePages,theme.name,true);else localStorage.setItem(storageKey(activeBook),JSON.stringify({version:1,pages:autoSavePages,theme:theme.name,updatedAt:new Date().toISOString()}))}catch{/* The visible tab reports storage errors during normal saving. */}};if(lastPersisted.current.book!==activeBook)lastPersisted.current={book:activeBook,signature:autoSaveSignature}},[screen,activeBook,autoSavePages,autoSaveSignature,theme.name,isCloud]);
 useDebouncedEffect(()=>{if(hydratedBook.current!==activeBook||lastPersisted.current.book===activeBook&&lastPersisted.current.signature===autoSaveSignature)return;persistPages(autoSavePages)},[activeBook,autoSaveSignature],1000,screen==="editor");
 useEffect(()=>{if(screen!=="editor")return;const pageId=currentPreview.id;if(history.current.pageId!==pageId){history.current={pageId,past:[],present:currentSerialized,future:[]};queueMicrotask(()=>{setCanUndo(false);setCanRedo(false)});return}const timer=window.setTimeout(()=>{if(history.current.present&&history.current.present!==currentSerialized){history.current.past=[...history.current.past.slice(-49),history.current.present];history.current.present=currentSerialized;history.current.future=[];setCanUndo(true);setCanRedo(false)}},450);return()=>window.clearTimeout(timer)},[screen,currentPreview.id,currentSerialized]);
 const restoreHistory=(serialized:string)=>{const restored=JSON.parse(serialized) as PageData;setPages(existing=>existing.length?existing.map((page,index)=>index===pageIndex?restored:page):[restored]);loadPage(restored,pageIndex)};
 const undo=()=>{const state=history.current,previous=state.past.at(-1);if(!previous)return;state.future=[state.present,...state.future];state.past=state.past.slice(0,-1);state.present=previous;restoreHistory(previous);setCanUndo(state.past.length>0);setCanRedo(true)};
 const redo=()=>{const state=history.current,next=state.future[0];if(!next)return;state.past=[...state.past,state.present];state.future=state.future.slice(1);state.present=next;restoreHistory(next);setCanUndo(true);setCanRedo(state.future.length>0)};
 const storeBooks=(next:Book[])=>{localStorage.setItem(BOOKS_STORAGE_KEY,JSON.stringify(next));setBooks(next)};
 const createBook=async()=>{if(isCloud&&cloudUserId){setLibraryBusy(true);try{const book=await createEncryptedJournal(cloudUserId,getAccountMasterKey(),{title:"Untitled Journal",tone:"kraft",label:"new memories"});setBooks(current=>[...current,book]);setLibraryMessage("Encrypted journal created.");openBook(book.id)}catch(error){setLibraryMessage(error instanceof Error?error.message:"The encrypted journal could not be created.")}finally{setLibraryBusy(false)}return}const id="book-"+crypto.randomUUID(),next=[...books,{id,title:"Untitled Journal",tone:"kraft",label:"new memories"}];try{storeBooks(next);openBook(id)}catch{setSaveError("The new journal could not be saved because browser storage is unavailable.")}};
 const updateBookMetadata=async(id:string,changes:Partial<Omit<Book,"id">>,successMessage:string)=>{const book=books.find(item=>item.id===id);if(isCloud&&book){setLibraryBusy(true);try{await updateEncryptedJournal(getAccountMasterKey(),book,changes);setBooks(current=>current.map(item=>item.id===id?{...item,...changes}:item));setLibraryMessage(successMessage)}catch(error){setLibraryMessage(error instanceof Error?error.message:"The encrypted journal could not be updated.")}finally{setLibraryBusy(false)}return}try{storeBooks(books.map(item=>item.id===id?{...item,...changes}:item))}catch{setSaveError("The journal could not be updated.")}};
 const renameBook=(id:string,newTitle:string)=>updateBookMetadata(id,{title:newTitle},"Encrypted journal renamed.");
 const changeBookTone=(id:string,tone:string)=>updateBookMetadata(id,{tone},"A new cover colour was saved.");
 const migrateLocal=async()=>{if(!cloudUserId||!migrationSources.length)return;setMigrationBusy(true);try{const sourceIds=migrationSources.map(source=>source.book.id);downloadMigrationBackup(migrationSources);const migrated=await migrateLocalJournals({userId:cloudUserId,masterKey:getAccountMasterKey(),sources:migrationSources});setBooks(current=>[...current,...migrated.filter(book=>!current.some(existing=>existing.id===book.id))]);setMigratedLocalIds(sourceIds);setMigrationSources(getLocalMigrationSources());setLibraryMessage(`${migrated.length} local ${migrated.length===1?"journal":"journals"} encrypted and moved. Local copies were kept.`)}catch(error){setLibraryMessage(error instanceof Error?error.message:"Local journals could not be migrated. Their local copies are safe.")}finally{setMigrationBusy(false)}};
 const removeMigratedLocal=()=>{if(!migratedLocalIds.length||!window.confirm("Remove the migrated local copies from this device? Your encrypted cloud journals and downloaded backup will remain."))return;const removed=removeMigratedLocalCopies(migratedLocalIds);setMigratedLocalIds([]);setLibraryMessage(`${removed} migrated local ${removed===1?"copy":"copies"} removed from this device.`)};
 const signOut=async()=>{setLibraryBusy(true);try{await createClient().auth.signOut({scope:"local"});await clearPersistedAccountMasterKey();for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key?.startsWith("pin-paper-cloud-draft-v2:"))localStorage.removeItem(key)}router.replace("/");router.refresh()}finally{setLibraryBusy(false)}};
 const deleteBook=async(book:Book)=>{if(!window.confirm(`Delete “${book.title}” and all of its ${isCloud?"encrypted cloud":"locally saved"} pages? This cannot be undone.`))return;if(isCloud){setLibraryBusy(true);try{await deleteEncryptedJournal(book.id);localStorage.removeItem(storageKey(book.id));setBooks(current=>current.filter(item=>item.id!==book.id));setLibraryMessage("Encrypted journal deleted.")}catch(error){setLibraryMessage(error instanceof Error?error.message:"The encrypted journal could not be deleted.")}finally{setLibraryBusy(false)}return}try{localStorage.removeItem(storageKey(book.id));storeBooks(books.filter(item=>item.id!==book.id))}catch{setSaveError("The journal could not be deleted.")}};
 const exportBackup=async()=>{if(isCloud){setLibraryBusy(true);setLibraryMessage("Preparing your decrypted, portable backup on this device…");try{downloadBackupFile(await makeCloudBackup(books,getAccountMasterKey()));setLibraryMessage("Backup downloaded. Keep it somewhere private.")}catch(error){setLibraryMessage(error instanceof Error?error.message:"The encrypted cloud backup could not be created.")}finally{setLibraryBusy(false)}return}try{downloadBackupFile(makeBackup(books,id=>localStorage.getItem(storageKey(id))))}catch{setSaveError("The local backup could not be created.")}};
 const importBackup=async(file:File)=>{try{const backup=parseBackup(await file.text());if(isCloud&&cloudUserId){if(!window.confirm(`Import ${backup.books.length} journals as new encrypted cloud journals? Existing journals will not be replaced.`))return;setLibraryBusy(true);setLibraryMessage("Encrypting and importing your backup…");try{const imported=await importCloudBackup({backup,userId:cloudUserId,masterKey:getAccountMasterKey()});setBooks(current=>[...current,...imported]);setLibraryMessage(`${imported.length} ${imported.length===1?"journal":"journals"} imported as encrypted cloud copies.`)}finally{setLibraryBusy(false)}return}if(!window.confirm(`Import ${backup.books.length} journals? This replaces the journals currently stored in this browser.`))return;for(const book of books)localStorage.removeItem(storageKey(book.id));for(const book of backup.books){const data=backup.journals[book.id];if(data)localStorage.setItem(storageKey(book.id),JSON.stringify(data))}storeBooks(backup.books);setSaveError("")}catch(error){if(isCloud)setLibraryMessage(error instanceof Error?error.message:"The cloud backup could not be imported.");else setSaveError(error instanceof Error?error.message:"The backup could not be imported.")}};
 if(screen==="shelf")return <JournalLibrary books={books} busy={libraryBusy} message={libraryMessage} localMigrationCount={migrationSources.length} migrationBusy={migrationBusy} migratedLocalCount={migratedLocalIds.length} onMigrateLocal={migrateLocal} onRemoveMigratedLocal={removeMigratedLocal} onCreate={createBook} onDelete={deleteBook} onExport={exportBackup} onImport={importBackup} onOpen={openBook} onRename={renameBook} onToneChange={changeBookTone} onSignOut={isCloud?signOut:undefined}/>;
 return <main className={"desk-screen "+(focus?"focus-mode ":"")+(pagePanelOpen?"page-panel-open ":"")+(selected!==null?"has-selection ":"")+(canUndo||canRedo?"has-history":"")} style={{"--ink":theme.color,"--wash":theme.pale} as React.CSSProperties}>
 <header className="topbar"><button className="back-library" onClick={()=>{if(save())setScreen("shelf")}}><BookOpen/> My journals</button><div className="page-history"><Button variant="ghost" size="icon" disabled={!canUndo} onClick={undo} title="Undo"><Undo2/></Button><Button variant="ghost" size="icon" disabled={!canRedo} onClick={redo} title="Redo"><Redo2/></Button><Button variant="ghost" size="icon" disabled={pageIndex===0} onClick={()=>movePage(-1)} title="Move page left"><ArrowLeft/></Button><Button variant="ghost" size="icon" disabled={pageIndex>=pages.length-1} onClick={()=>movePage(1)} title="Move page right"><ArrowRight/></Button><Button variant="ghost" size="icon" onClick={deletePage} title="Delete page"><Trash2/></Button></div><div className="page-nav"><Button variant="ghost" size="icon" disabled={previousTarget<0} onClick={()=>goPage(previousTarget)}><ChevronLeft/></Button><span>{singlePage?(pageName||`Page ${pageIndex+1}`):`Pages ${spreadStart+1}–${Math.min(spreadStart+2,Math.max(1,pages.length))}`}</span><Button variant="ghost" size="icon" disabled={nextTarget>=Math.max(1,pages.length)} onClick={()=>goPage(nextTarget)}><ChevronRight/></Button><Button variant="outline" size="sm" onClick={addPage}><Plus/> New page</Button><Button variant="ghost" size="sm" className="page-panel-toggle" aria-expanded={pagePanelOpen} onClick={()=>setPagePanelOpen(open=>!open)}><FileText/> Pages</Button></div><Button variant="ghost" size="icon" onClick={()=>setFocus(v=>!v)} title="Focus mode" aria-label="Focus mode"><Focus/></Button><Button variant="outline" onClick={sharePage}><Share2/> <span>Export page</span></Button><Button variant="ghost" size="icon" onClick={()=>setSyncHistoryOpen(open=>!open)} title="Sync history" aria-label="Sync history"><History/></Button><Button onClick={save} className="save-button" aria-live="polite">{saveState==="saving"?"Saving…":saveState==="saved"?"Saved quietly ♡":saveState==="offline"?"Saved on this device ♡":saveState==="error"?"Try saving again":"Save"}</Button></header>
  {saveError&&<AppNotice message={saveError} kind={saveState==="offline"?"warning":"error"} onRetry={saveState==="error"?save:undefined} onDismiss={()=>setSaveError("")}/>}
  {syncHistoryOpen&&<aside className="sync-history-panel" aria-label="Sync history"><div><strong>Sync history</strong><button type="button" onClick={()=>setSyncHistoryOpen(false)} aria-label="Close sync history">×</button></div>{syncEvents.length?syncEvents.map((event,index)=><p key={`${event.at}-${index}`}><span className={`sync-dot ${event.status}`}/><time>{new Date(event.at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"})}</time><b>{event.status}</b>{event.code?<small>{event.code}</small>:null}</p>):<p>No sync attempts in this tab yet.</p>}</aside>}
  <PageFinder activeIndex={pageIndex} onAdd={addPage} onSelect={index=>{goPage(index);if(singlePage)setPagePanelOpen(false)}} pages={pages.length?pages:[currentPreview]} query={pageSearch} setQuery={setPageSearch} onMoveLeft={()=>movePage(-1)} onMoveRight={()=>movePage(1)} onDelete={deletePage} canMoveLeft={pageIndex>0} canMoveRight={pageIndex<pages.length-1}/>
  <div className="workspace"><nav className="page-tabs">{["Today","Dreams","Us","Ideas"].map((x,i)=><button key={x} className={i===pageIndex?"active":""} onClick={()=>i<pages.length&&goPage(i)}>{x}</button>)}<button onClick={addPage}>＋</button></nav><aside className="toolbox" data-tool={tool}><div className="tool-rail">{[{id:"write",icon:<Type/>,n:"Write"},{id:"photos",icon:<Images/>,n:"Photos"},{id:"stickers",icon:<Sparkles/>,n:"Stickers"},{id:"draw",icon:<Brush/>,n:"Draw"},{id:"paper",icon:<FileText/>,n:"Paper"}].map(t=><button key={t.id} className={tool===t.id?"active":""} aria-expanded={tool===t.id} onClick={()=>setTool(current=>singlePage&&current===t.id?"":t.id)}>{t.icon}<span>{t.n}</span></button>)}</div><div className="tool-drawer"><button className="drawer-close" onClick={()=>setTool("")} aria-label="Close creative drawer"><X/></button><div className="tape">creative drawer</div>
   <section className="tool-stickers"><h2><Sparkles size={16}/> Sticker library</h2><p>Drag onto the page, or tap to add.</p><StickerCatalog onAdd={addSticker}/>{activeSticker&&<div className="object-tools"><strong>Edit selected</strong><label>Size <input type="range" min="24" max="260" value={activeSticker.size||52} onChange={e=>setPlaced(items=>items.map(item=>item.id===activeSticker.id?{...item,size:+e.target.value}:item))}/></label><label>Rotate <input type="range" min="-180" max="180" value={activeSticker.rotation} onChange={e=>setPlaced(items=>items.map(item=>item.id===activeSticker.id?{...item,rotation:+e.target.value}:item))}/></label>{activeSticker.kind==="tape"&&<label>Opacity <span className="range-with-value"><input type="range" min="10" max="100" value={Math.round((activeSticker.opacity??.82)*100)} onChange={e=>setPlaced(items=>items.map(item=>item.id===activeSticker.id?{...item,opacity:+e.target.value/100}:item))}/><b>{Math.round((activeSticker.opacity??.82)*100)}%</b></span></label>}<div><Button size="sm" variant="outline" onClick={()=>setPlaced(items=>items.map(item=>item.id===activeSticker.id?{...item,z:Math.max(...items.map(entry=>entry.z||0))+1}:item))}>Bring front</Button><Button size="sm" variant="outline" onClick={()=>setPlaced(items=>items.map(item=>item.id===activeSticker.id?{...item,z:Math.min(...items.map(entry=>entry.z||0))-1}:item))}>Send back</Button><Button size="sm" variant="ghost" onClick={()=>{setPlaced(items=>items.filter(item=>item.id!==activeSticker.id));setSelectedSticker(null)}}><Trash2/> Delete</Button></div></div>}</section>
   <section className="tool-paper"><h2><Palette size={16}/> Page design</h2><div className="template-picker">{([['free','Free writing'],['habit','Habit tracker'],['mood','Mood tracker'],['weekly','Weekly planner'],['todo','To-do checklist']] as [JournalTemplate,string][]).map(([id,label])=><button key={id} className={template===id?"active":""} onClick={()=>{if(id!==template){setTemplate(id);setTemplateTitle(DEFAULT_TEMPLATE_TITLES[id])}}}>{label}</button>)}</div>{template!=="free"&&<div className="object-tools template-controls"><strong>Template size</strong><label>Width <span className="range-with-value"><input type="range" min="40" max="92" value={templateLayout.width} onChange={e=>setTemplateLayout(layout=>({...layout,width:+e.target.value}))}/><b>{templateLayout.width}%</b></span></label><label>Height <span className="range-with-value"><input type="range" min="25" max="65" value={templateLayout.height} onChange={e=>setTemplateLayout(layout=>({...layout,height:+e.target.value}))}/><b>{templateLayout.height}%</b></span></label><Button size="sm" variant="ghost" onClick={()=>setTemplateLayout(DEFAULT_TEMPLATE_LAYOUT)}>Reset position & size</Button></div>}<h2 className="subhead">Colour mood</h2><div className="swatches">{themes.map(t=><button key={t.name} onClick={()=>setTheme(t)} className={theme.name===t.name?"active":""} style={{background:t.color}} aria-label={t.name}/>)}</div><h2 className="subhead">Paper surface</h2><div className="paper-scope" role="group" aria-label="Apply paper colour to"><button className={paperScope==="page"?"active":""} onClick={()=>setPaperScope("page")}>This page</button><button className={paperScope==="journal"?"active":""} onClick={()=>setPaperScope("journal")}>All pages</button></div><div className="paper-modes">{paperModes.map(mode=><button key={mode.name} className={paperColor===mode.color?"active":""} style={{background:mode.color}} onClick={()=>applyPaperColor(mode.color)} aria-label={`${mode.name} paper`}/>) }<label className="custom-paper" title="Custom paper colour"><Brush/><input type="color" value={paperColor} onChange={e=>applyPaperColor(e.target.value)} aria-label="Custom paper colour"/></label></div><div className="compact-controls"><select value={pattern} onChange={e=>applyPaperPattern(e.target.value)}><option value="lined">Lined</option><option value="dots">Dotted</option><option value="grid">Grid</option><option value="plain">Plain</option><option value="retro">Aged parchment</option></select></div></section>
   <section className="tool-write"><h2>𝑨 Writing style</h2><div className="compact-controls"><select value={font} onChange={e=>setFont(e.target.value)}><option value="hand">Handwritten</option><option value="ink">Artistic ink</option><option value="serif">Classic serif</option><option value="sans">Clean sans</option><option value="mono">Typewriter</option></select><label>Size <input type="range" min="12" max="34" value={fontSize} onChange={e=>setFontSize(+e.target.value)}/><b>{fontSize}</b></label><label>Text colour <input type="color" value={textColor} onChange={e=>setTextColor(e.target.value)} aria-label="Page text colour"/></label>{joysVisible?<div className="card-style-controls"><strong>List card</strong><label>Heading <input value={joyTitle} maxLength={32} onChange={e=>setJoyTitle(e.target.value)}/></label><label>Card colour <input type="color" value={joyColor} onChange={e=>setJoyColor(e.target.value)}/></label><label>Text colour <input type="color" value={joyTextColor} onChange={e=>setJoyTextColor(e.target.value)}/></label></div>:<Button variant="outline" size="sm" onClick={()=>setJoysVisible(true)}>＋ Add list card</Button>}</div></section>
   <section className="tool-photos"><h2><ImagePlus size={16}/> Photos</h2><p>{assetProgress?`Processing ${assetProgress.completed}/${assetProgress.total}…`:"Add several, then arrange them freely."}</p><label className="upload"><input multiple type="file" accept="image/*" onChange={e=>upload(e.target.files)}/><ImagePlus size={18}/> Add pictures</label>{brokenPhotoCount>0&&<Button variant="outline" size="sm" onClick={repairAllPhotos} disabled={Boolean(assetProgress)}>Repair {brokenPhotoCount} broken {brokenPhotoCount===1?"photo":"photos"}</Button>}{saveState==="error"&&photos.some(photo=>!photo.assetId)&&<Button variant="outline" size="sm" onClick={save}>Retry pending uploads</Button>}
    {active&&<div className="photo-tools"><label className="size-control">Size <input type="range" min="80" max="420" value={active.size||180} onChange={e=>editPhoto(p=>({...p,size:+e.target.value}))}/></label><label className="size-control rotate-control">Rotate <input type="range" min="-180" max="180" value={active.rotation} onChange={e=>editPhoto(p=>({...p,rotation:+e.target.value}))}/><input className="rotation-number" type="number" min="-180" max="180" value={active.rotation} onChange={e=>editPhoto(p=>({...p,rotation:Math.max(-180,Math.min(180,+e.target.value||0))}))} aria-label="Photo rotation degrees"/><b>°</b></label><label className="shape-control">Shape <select value={active.shape||"square"} onChange={e=>editPhoto(p=>({...p,shape:e.target.value as Photo["shape"]}))}><option value="square">Square</option><option value="round">Circle</option><option value="soft">Soft corners</option><option value="wavy">Wavy</option></select></label><Button variant="outline" size="sm" onClick={()=>editPhoto(p=>({...p,framed:!p.framed}))}><Frame/> {active.framed?"Remove frame":"Add frame"}</Button><Button variant="outline" size="sm" onClick={()=>editPhoto(p=>({...p,z:Math.max(...photos.map(x=>x.z))+1}))}><Layers/> Bring front</Button><Button variant="outline" size="sm" onClick={()=>{revokeEncryptedAssetUrl(active.src);setPhotos(a=>a.filter(p=>p.id!==selected));setSelected(null)}}><Trash2/> Delete</Button></div>}
   </section>
   <section className="tool-draw"><h2><Brush size={16}/> Drawing studio</h2><div className="pen-types">{([['fine','Fine liner'],['pencil','Pencil'],['highlighter','Highlighter'],['brush','Brush']] as [PenType,string][]).map(([id,label])=><button key={id} className={penType===id?"active":""} onClick={()=>setPenType(id)}>{label}</button>)}</div><div className="pen-palette">{penPalette.map(color=><button key={color} className={penColor===color?"active":""} style={{background:color}} onClick={()=>setPenColor(color)} aria-label={`Ink ${color}`}/>)}</div><div className="draw-tools"><Button size="sm" variant={drawing?"default":"outline"} onClick={()=>setDrawing(v=>!v)}>{drawing?"Drawing on":"Start drawing"}</Button><Button size="sm" variant="outline" onClick={addFreeText}><Type/> Free text</Button><Button size="sm" variant="ghost" onClick={clearDrawing}>Erase all</Button></div>{activeText&&<div className="object-tools"><label>Text size <input type="range" min="12" max="48" value={activeText.size} onChange={e=>setFreeTexts(items=>items.map(item=>item.id===activeText.id?{...item,size:+e.target.value}:item))}/></label><label>Rotate <input type="range" min="-30" max="30" value={activeText.rotation} onChange={e=>setFreeTexts(items=>items.map(item=>item.id===activeText.id?{...item,rotation:+e.target.value}:item))}/></label><Button size="sm" variant="ghost" onClick={()=>{setFreeTexts(items=>items.filter(item=>item.id!==activeText.id));setSelectedText(null)}}><Trash2/> Delete text</Button></div>}</section>
   <Button variant="ghost" className="clear-button" onClick={clearDecorations}><RotateCcw size={15}/> Clear decorations</Button>
  </div></aside>
  <section className="journal-shell">
   <div className={"book-spread "+(turning?"spread-turn-"+turning:"")}>
   {!singlePage&&(companion?<div role="button" tabIndex={0} aria-label={`Edit page ${companionIndex+1}`} className={"companion-page paper-"+(companion.pattern||"lined")+" "+(companion.paperColor==="#11100f"?"paper-dark ":"")+"side-"+(companionIndex%2?"right":"left")} style={{backgroundColor:companion.paperColor||"#fffdf7","--page-text-color":companion.textColor||"#66564b"} as React.CSSProperties} onClick={()=>selectPage(companionIndex)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();selectPage(companionIndex)}}}>
    <span className="companion-number">{companionIndex+1}</span>
    <div className="page-identity saved-identity"><label><span>Page name</span><em>{companion.pageName||`Page ${companionIndex+1}`}</em></label><label><span>Date</span><em>{companion.pageDate||"No date"}</em></label></div>
    <div className="date-row"><span>{companion.pageDate?new Intl.DateTimeFormat("en",{weekday:"long",month:"long",day:"numeric"}).format(new Date(companion.pageDate+"T12:00:00")):"Undated page"}</span></div>
    <div className="journal-title saved-title">{companion.title}</div>
    <div className="content-grid"><div className={"writing-area font-"+(companion.font||"hand")}><div className="saved-note" style={{fontSize:pageScaledPixels(companion.fontSize||18),color:companion.textColor||"#66564b",lineHeight:pageScaledPixels(Math.max(32,Math.ceil((companion.fontSize||18)*1.55)))}}>{companion.note||"Write freely…"}</div></div>{companion.joysVisible!==false&&<div className="tiny-list saved-joys" style={{left:(companion.joyPosition?.x??53)+"%",top:(companion.joyPosition?.y??61)+"%",backgroundColor:companion.joyColor||"#eee2a9",color:companion.joyTextColor||"#66564b"}}><b style={{color:companion.joyTextColor||"#66564b"}}>{companion.joyTitle||"little joys"}</b>{(companion.joys||[]).map(j=><div className="saved-joy" key={j.id}><span className={j.done?"done":""}>{j.text}</span></div>)}</div>}</div>
    <JournalTemplateLayer template={companion.template} title={companion.templateTitle} checks={companion.trackerChecks} todoItems={companion.todoItems} moodEntries={companion.moodEntries} layout={companion.templateLayout||DEFAULT_TEMPLATE_LAYOUT} readOnly/>
    <blockquote>“collect moments, not things”</blockquote>
    {companion.drawingData&&<img className="saved-drawing" src={companion.drawingData} alt=""/>}
    {(companion.photos||[]).map(p=><span key={p.id} className={"placed-photo saved-photo shape-"+(p.shape||"square")+(p.framed?" framed":"")} style={{left:p.x+"%",top:p.y+"%",width:photoSizePercent(p.size)+"%",zIndex:p.z,transform:`rotate(${p.rotation}deg)`}}>{p.src?<img src={p.src} alt=""/>:<span className="photo-error-card"><Images/><small>Photo unavailable</small></span>}</span>)}
    {(companion.placed||[]).map(s=><span key={s.id} className={`placed-sticker saved-sticker kind-${s.kind||"sticker"} tape-${s.value} category-${(s.category||"").toLowerCase()}`} style={{left:s.x+"%",top:s.y+"%",width:(s.size||52)+"px",fontSize:(s.kind==="tape"?0:s.size||52)+"px",zIndex:s.z||0,opacity:s.opacity??(s.kind==="tape"?.82:1),transform:`rotate(${s.rotation}deg)`}}>{s.value}</span>)}
    {(companion.freeTexts||[]).map(text=><span key={text.id} className="free-text saved-free-text" style={{left:text.x+"%",top:text.y+"%",fontSize:text.size+"px",zIndex:text.z,transform:`rotate(${text.rotation}deg)`}}>{text.text}</span>)}
   </div>:<button className={"companion-page blank-companion side-"+(companionIndex%2?"right":"left")} onClick={addPage}><Plus/><span>Add page {companionIndex+1}</span></button>)}
   <div className={"journal-page active-leaf side-"+(pageIndex%2?"right ":"left ")+"paper-"+pattern+" "+(paperColor==="#11100f"?"paper-dark ":"")+(drawing?"drawing-mode ":"")+(turning?"turn-"+turning:"")} style={{backgroundColor:paperColor,"--page-text-color":textColor} as React.CSSProperties} ref={pageRef} onDragOver={event=>event.preventDefault()} onDrop={dropCatalogSticker} onPointerMove={move} onPointerUp={()=>drag.current=null} onPointerLeave={()=>drag.current=null}>
    <span className="companion-number">{pageIndex+1}</span>
    <div className="page-identity"><label><span>Page name</span><input value={pageName} onChange={e=>setPageName(e.target.value)} placeholder="Today, Dreams, Us…"/></label><label><span>Date</span><input type="date" value={pageDate} onChange={e=>setPageDate(e.target.value)}/></label></div>
    <div className="date-row"><span>{pageDate?new Intl.DateTimeFormat("en",{weekday:"long",month:"long",day:"numeric"}).format(new Date(pageDate+"T12:00:00")):"Undated page"}</span></div>
    <textarea className="journal-title" rows={2} aria-label="Page title" value={title} onChange={e=>setTitle(e.target.value)}/>
    <div className="content-grid"><div className={"writing-area font-"+font}><Textarea style={{fontSize:pageScaledPixels(fontSize),color:textColor,"--journal-line-height":pageScaledPixels(Math.max(32,Math.ceil(fontSize*1.55)))} as React.CSSProperties} value={note} onChange={e=>setNote(e.target.value)} placeholder={"Write freely…\n\nWhat made you smile today?\nWhat are you dreaming about?"}/></div>{joysVisible&&<div className="tiny-list" style={{left:joyPosition.x+"%",top:joyPosition.y+"%",backgroundColor:joyColor,color:joyTextColor}}><button className="remove-joys" onClick={()=>setJoysVisible(false)} title="Remove list card">×</button><b className="joy-drag-handle" style={{color:joyTextColor}} title="Drag list card" onPointerDown={e=>beginDrag(e,"joy",0)}>{joyTitle||"notes"}</b>{joys.map(j=><div className="joy-row" key={j.id}><input value={j.text} style={{color:joyTextColor}} className={j.done?"done":""} aria-label={`${j.done?"Remove strikethrough from":"Strikethrough"} ${j.text}`} onClick={()=>setJoys(a=>a.map(x=>x.id===j.id?{...x,done:!x.done}:x))} onChange={e=>setJoys(a=>a.map(x=>x.id===j.id?{...x,text:e.target.value}:x))}/><button className="remove-joy" aria-label={`Delete ${j.text}`} onClick={()=>setJoys(a=>a.filter(x=>x.id!==j.id))}>×</button></div>)}<button className="add-joy" style={{color:joyTextColor}} onClick={()=>setJoys(a=>[...a,{id:Date.now(),text:"new item",done:false}])}>+ add item</button></div>}</div><blockquote>“collect moments, not things”</blockquote>
    <JournalTemplateLayer template={template} title={templateTitle} checks={trackerChecks} todoItems={todoItems} moodEntries={moodEntries} layout={templateLayout} onMoveStart={e=>beginDrag(e,"template",0)} onTitleChange={setTemplateTitle} onToggle={index=>setTrackerChecks(items=>{const next=[...items];next[index]=!next[index];return next})} onTodoAdd={()=>setTodoItems(items=>[...items,{id:Date.now(),text:"",done:false}])} onTodoChange={(id,text)=>setTodoItems(items=>items.map(item=>item.id===id?{...item,text}:item))} onTodoToggle={id=>setTodoItems(items=>items.map(item=>item.id===id?{...item,done:!item.done}:item))} onTodoDelete={id=>setTodoItems(items=>items.filter(item=>item.id!==id))} onMoodChange={(index,entry)=>setMoodEntries(items=>{const next=[...items];next[index]=entry;return next})}/>
    <canvas ref={canvasRef} className="drawing-canvas" onPointerDown={startDraw} onPointerMove={draw} onPointerUp={finishDrawing} onPointerLeave={finishDrawing}/>
    {photos.map(p=><div key={p.id} role="group" tabIndex={0} aria-label="Journal photo" className={"placed-photo shape-"+(p.shape||"square")+" "+(p.framed?"framed ":"")+(selected===p.id?"selected":"")} style={{left:p.x+"%",top:p.y+"%",width:photoSizePercent(p.size)+"%",transform:`rotate(${p.rotation}deg)`,zIndex:10+p.z}} onClick={()=>setSelected(p.id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(p.id)}}} onPointerDown={e=>{setSelected(p.id);beginDrag(e,"photo",p.id)}}>{p.src?<img src={p.src} alt="Journal memory" onError={e=>{if(e.currentTarget.dataset.repairing)return;e.currentTarget.dataset.repairing="true";void repairPhoto(p)}}/>:<div className="photo-error-card" role="alert"><Images/><small>{p.loadError?"Photo unavailable":"Opening photo…"}</small>{p.assetId&&<button type="button" onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();void repairPhoto(p)}} disabled={repairingPhotos.has(p.id)}>{repairingPhotos.has(p.id)?"Retrying…":"Retry"}</button>}</div>}</div>)}
    {placed.map(s=><button key={s.id} aria-label={s.kind==="tape"?`${s.value} washi tape`:`${s.value} sticker`} className={`placed-sticker kind-${s.kind||"sticker"} tape-${s.value} category-${(s.category||"").toLowerCase()} ${selectedSticker===s.id?"selected":""}`} style={{left:s.x+"%",top:s.y+"%",width:(s.size||52)+"px",fontSize:(s.kind==="tape"?0:s.size||52)+"px",zIndex:40+(s.z||0),opacity:s.opacity??(s.kind==="tape"?.82:1),transform:`rotate(${s.rotation}deg)`}} onClick={()=>{setSelectedSticker(s.id);setSelected(null);setSelectedText(null)}} onPointerDown={e=>{setSelectedSticker(s.id);beginDrag(e,"sticker",s.id)}}>{s.value}</button>)}
    {freeTexts.map(text=><textarea key={text.id} aria-label="Free text box" className={`free-text ${selectedText===text.id?"selected":""}`} value={text.text} onChange={e=>setFreeTexts(items=>items.map(item=>item.id===text.id?{...item,text:e.target.value}:item))} onClick={()=>{setSelectedText(text.id);setSelected(null);setSelectedSticker(null)}} onPointerDown={e=>{if(e.currentTarget===document.activeElement)return;setSelectedText(text.id);beginDrag(e,"text",text.id)}} style={{left:text.x+"%",top:text.y+"%",fontSize:text.size+"px",zIndex:45+text.z,transform:`rotate(${text.rotation}deg)`}}/>) }
   </div></div><p className="hint">{drawing?"Draw directly on the page. Turn drawing off to move items.":"Tap either page to edit it. Move forward to open the next two pages."}</p>
  </section></div>
 </main>
}
